pragma Singleton
import Quickshell
import QtQuick

Singleton {
    readonly property var languageOptions: [{
        "id": "ko",
        "label": "한국어"
    }, {
        "id": "en",
        "label": "English"
    }]
    readonly property var ko: ({
        "Stocks": "주식",
        "Layout": "레이아웃",
        "Large": "라지",
        "Dashboard": "대시보드",
        "Market News": "주식 뉴스",
        "Company": "기업",
        "Company event": "기업 직접",
        "Product": "제품·서비스",
        "Supply chain": "공급망",
        "Competitor": "경쟁사",
        "Regulation": "규제·정책",
        "Macro": "거시 환경",
        "Industry": "산업",
        "Official source": "공식 출처",
        "Top-tier source": "최상위 출처",
        "Established source": "주요 언론",
        "Aggregator": "뉴스 모음",
        "Low-confidence source": "낮은 신뢰 출처",
        "%1 independent sources": "독립 출처 %1곳",
        "%1 reports grouped": "유사 기사 %1건 묶음",
        "Today": "오늘",
        "Yesterday": "어제",
        "Two days ago": "이틀 전",
        "Updated %1": "%1 업데이트",
        "Cached · Updated %1": "캐시 · %1 업데이트",
        "Up to 3 days": "최근 3일",
        "Loading market news…": "주식 뉴스를 불러오는 중…",
        "No market news from the last three days.": "최근 3일간 관련 주식 뉴스가 없습니다.",
        "No news about %1 from the last three days.": "최근 3일간 %1 관련 뉴스가 없습니다.",
        "No news for this day.": "이 날의 관련 뉴스가 없습니다.",
        "Could not load market news.": "주식 뉴스를 불러오지 못했습니다.",
        "Could not read market news.": "주식 뉴스 데이터를 읽지 못했습니다.",
        "Live": "실시간",
        "TOTAL": "총 자산",
        "CASH": "현금",
        "BUYABLE": "매수 가능",
        "Language": "언어",
        "Symbol": "종목 코드",
        "Market": "시장",
        "Default Range": "기본 차트 기간",
        "Data Source": "데이터 소스",
        "KIS Environment": "한국투자증권 환경",
        "Korea": "한국",
        "Quick": "빠르게",
        "Balanced": "균형",
        "Deep": "정밀",
        "Demo": "데모",
        "KIS Live": "KIS 실시간",
        "Paper": "모의투자",
        "Production": "실전투자",
        "Off": "끔",
        "Both": "둘 다",
        "Background Monitoring": "백그라운드 모니터링",
        "Background monitoring and quant observer are running": "백그라운드 모니터링과 퀀트 관찰기가 실행 중입니다",
        "Global": "전체",
        "Keychain Ready": "키체인 준비됨",
        "Keychain": "키체인",
        "Trade Ready": "거래 준비됨",
        "Quotes Ready": "시세 준비됨",
        "Not Saved": "저장되지 않음",
        "App Key": "앱 키",
        "App Secret": "앱 시크릿",
        "Account Number (8-2)": "계좌번호 (8-2)",
        "Production Orders": "실전 주문",
        "Enabled": "활성화됨",
        "Locked": "잠김",
        "Risk Guard": "위험 제한",
        "Per order · KRW": "주문당 한도 · 원",
        "Daily buys · KRW": "일일 매수 한도 · 원",
        "Buy orders / day": "일일 매수 횟수",
        "Max position · %": "종목당 최대 비중 · %",
        "Auto order limit": "자동 주문 한도",
        "Daily auto exposure": "일일 자동 신규노출",
        "Auto orders per day": "일일 자동 주문",
        "Auto max position": "자동 종목당 비중",
        "Cash reserve": "현금 보유",
        "count": "회",
        "Paper transaction cost assumptions": "모의투자 거래비용 가정",
        "KRX commission": "국장 수수료",
        "KRX sell tax": "국장 매도세",
        "US commission": "미장 수수료",
        "US sell fees": "미장 매도 부대비용",
        "Slippage": "슬리피지",
        "AI Provider": "AI 제공자",
        "Analysis Quality": "분석 품질",
        "Syncing": "동기화 중",
        "Refresh": "새로고침",
        "OpenAI API Key": "OpenAI API 키",
        "Claude API Key": "Claude API 키",
        "Saved": "저장됨",
        "Replace saved value": "저장된 값 교체",
        "Enter securely": "안전하게 입력",
        "Save": "저장",
        "Saving…": "저장 중…",
        "Lock": "잠그기",
        "Enable": "활성화",
        "Trade": "주문",
        "AI Insight": "AI 분석",
        "Portfolio": "보유 자산",
        "Buy": "매수",
        "Sell": "매도",
        "Market Order": "시장가",
        "Limit Order": "지정가",
        "Limit": "지정가",
        "SIDE": "주문 구분",
        "QUANTITY": "수량",
        "ORDER TYPE": "주문 유형",
        "LIMIT PRICE": "지정가",
        "ESTIMATED TOTAL": "예상 주문 금액",
        "ESTIMATED": "예상 금액",
        "AVAILABLE": "주문 가능",
        "POSITION AFTER": "주문 후 보유 비중",
        "Cancel": "취소",
        "Confirm": "확인",
        "Review Order": "주문 확인",
        "Submit Order": "주문 제출",
        "Keep Order": "주문 유지",
        "Cancel Remaining Order": "미체결 주문 취소",
        "Activity": "거래 기록",
        "Trade Activity": "거래 기록",
        "All": "전체",
        "Accepted": "접수 완료",
        "Failed": "실패",
        "Submitting": "제출 중",
        "Verify": "확인 필요",
        "ACCEPTED": "접수 완료",
        "FAILED": "실패",
        "SUBMITTING": "제출 중",
        "VERIFY": "확인 필요",
        "MATCHED": "KIS 대조",
        "FILLED": "체결 완료",
        "OPEN": "진행 중",
        "Unknown": "알 수 없음",
        "Cancel order #%1": "주문 #%1 취소",
        "%1 %2 shares of %3": "%3 · %1 %2주",
        "Broker order #%1": "증권사 주문 #%1",
        "Broker order #%1 · %2/%3 filled": "증권사 주문 #%1 · %2/%3주 체결",
        "Broker order #%1 · reconciled": "증권사 주문 #%1 · 대조 완료",
        "Waiting for KIS confirmation": "KIS 주문 반영을 기다리는 중입니다",
        "Matched with KIS · updated %1": "KIS 거래내역 대조 완료 · %1 갱신",
        "KIS reconciliation unavailable · local audit shown": "KIS 대조 실패 · 로컬 기록을 표시합니다",
        "Estimated %1": "예상 금액 %1",
        "Final broker state is unknown; verify with KIS.": "최종 주문 상태를 확인할 수 없습니다. KIS에서 확인하세요.",
        "Local audit event": "로컬 거래 기록",
        "Falls below": "하향 이탈",
        "Rises above": "상향 돌파",
        "Filled": "체결 완료",
        "Partially filled": "부분 체결",
        "Pending": "미체결",
        "Canceled": "취소됨",
        "Rejected": "거절됨",
        "Submitted": "제출됨",
        "Automation": "자동화",
        "AI Autopilot": "AI 자동매매",
        "Autopilot": "자동매매",
        "Automatic Trading": "자동매매",
        "AUTOMATIC TRADING": "자동매매",
        "Automatic trading is on": "자동매매 켜짐",
        "Automatic trading is off": "자동매매 꺼짐",
        "Start Automatic Trading": "자동매매 시작",
        "Stop Automatic Trading": "자동매매 중지",
        "Set Up Automatic Trading": "자동매매 설정",
        "Connect KIS to start": "KIS 연결 후 시작",
        "Automatic Trading Details": "자동매매 상세",
        "Try Again": "다시 시도",
        "Refresh Now": "지금 새로고침",
        "Holdings": "보유 종목",
        "Today's P&L": "오늘 손익",
        "Next Check": "다음 검사",
        "%1 stocks": "%1종목",
        "When market opens": "장 시작 후",
        "Soon": "곧",
        "Within a minute": "1분 이내",
        "Turning automatic trading off…": "자동매매를 끄는 중…",
        "Starting automatic trading…": "자동매매를 시작하는 중…",
        "Checking news, trends, and candidates…": "뉴스·최근 동향·후보 종목을 확인하는 중…",
        "Automatic trading paused. Press Try Again to recover.": "자동매매가 잠시 멈췄어요. 다시 시도를 누르면 복구합니다.",
        "Trading is paused to protect your account. Open Details to review it.": "계좌 보호를 위해 거래를 멈췄어요. 상세에서 확인해 주세요.",
        "Check your account or API settings, then press Refresh Now.": "계좌 또는 API 설정을 확인한 뒤 지금 새로고침을 눌러 주세요.",
        "Protecting your holdings. New purchases will resume after conditions recover.": "보유 종목을 보호하는 중이에요. 조건이 회복되면 신규 매수를 재개합니다.",
        "Checking the latest order and holdings before continuing.": "계속하기 전에 최근 주문과 보유 종목을 확인하고 있어요.",
        "The connection is being checked again automatically.": "연결을 자동으로 다시 확인하고 있어요.",
        "The market is closed. Trading starts automatically when it opens.": "장이 닫혀 있어요. 장이 열리면 자동으로 시작합니다.",
        "Checking news and trends to find suitable stocks.": "뉴스와 최근 동향을 확인해 적합한 종목을 찾고 있어요.",
        "A rapid drop was detected, so your holding is being protected.": "급락을 감지해 보유 종목을 보호하고 있어요.",
        "An order was sent. Its result is being checked.": "주문을 보냈어요. 체결 결과를 확인하고 있어요.",
        "Automatic trading is monitoring the market and your holdings.": "시장과 보유 종목을 자동으로 확인하고 있어요.",
        "Automatic trading is off. Turn it on to start.": "자동매매가 꺼져 있어요. 스위치를 켜면 시작합니다.",
        "News, trends, stock selection, buying, and loss protection run automatically.": "뉴스·동향 분석부터 종목 선택, 매수, 손실 보호까지 자동으로 진행합니다.",
        "You choose the stocks; monitoring, buying, and loss protection run automatically.": "종목만 직접 고르면 감시, 매수, 손실 보호는 자동으로 진행합니다.",
        "Automatic Stock Selection": "종목 자동 선택",
        "AI picks stocks after checking news, trends, and risk.": "AI가 뉴스·동향·위험을 확인한 뒤 종목을 선택합니다.",
        "Select stocks directly from the list below.": "아래 목록에서 거래할 종목을 직접 선택합니다.",
        "Candidate Stocks": "후보 종목",
        "Check Now": "지금 확인",
        "Press Check Now to find candidate stocks.": "지금 확인을 눌러 후보 종목을 찾으세요.",
        "Status Details": "상태 상세",
        "Stock Selection": "종목 선택",
        "Last Check": "최근 검사",
        "Background Check": "백그라운드 검사",
        "Checks holding this trade · %1": "이번 거래를 보류한 조건 · %1",
        "Loss Limit": "손실 제한",
        "Needs attention": "확인 필요",
        "Good": "정상",
        "Safety & Limits": "안전 및 한도",
        "Real orders can lose money. Every order is checked before it is sent.": "실전 주문에는 손실 위험이 있습니다. 모든 주문은 전송 직전에 다시 확인합니다.",
        "Paper results can differ from real trading. Returns are not guaranteed.": "모의투자 결과는 실전과 다를 수 있으며 수익은 보장되지 않습니다.",
        "Paused for Safety": "안전을 위해 일시 정지",
        "Checking": "확인 중",
        "Trading Mode": "거래 모드",
        "Manual": "수동",
        "Auto": "자동",
        "Trading Candidates": "거래 종목",
        "AI Candidate Selection": "AI 종목 자동선정",
        "Manual Candidate Selection": "직접 종목 선택",
        "Start KIS Paper Auto": "KIS 모의 자동매매 시작",
        "Stop KIS Paper Auto": "KIS 모의 자동매매 중지",
        "Review Live Auto": "실전 자동매매 확인",
        "Review Live Auto Trading": "실전 자동매매 시작 확인",
        "Start Live Auto Trading": "실전 자동매매 시작",
        "Stop Live Auto Trading": "실전 자동매매 중지",
        "Review Safety Halt": "안전 중지 확인",
        "Auto Trading Settings": "자동매매 설정",
        "KIS PAPER AUTO": "KIS 모의 자동매매",
        "KIS LIVE AUTO": "KIS 실전 자동매매",
        "KIS Production": "KIS 실전투자",
        "KIS production account · actual broker orders": "KIS 실전 계좌 · 실제 증권사 주문",
        "Actual funds will be traded. Market gaps, latency, and partial fills can exceed configured loss limits. Safety gates reduce risk but cannot prevent losses or guarantee returns.": "실제 자금으로 매수·매도합니다. 시장 갭, 지연, 부분 체결로 설정한 손실 한도를 초과할 수 있습니다. 안전 게이트는 위험을 줄이지만 손실을 막거나 수익을 보장할 수 없습니다.",
        "Candidates": "후보 종목",
        "Markets": "대상 시장",
        "Per-order limit": "주문당 한도",
        "Daily exposure limit": "일일 신규노출 한도",
        "Daily loss halt": "일일 손실 중지",
        "Portfolio drawdown halt": "포트폴리오 낙폭 중지",
        "Type START LIVE AUTO to authorize this live session.": "이번 실전 세션을 승인하려면 START LIVE AUTO를 입력하세요.",
        "Starting…": "시작 중…",
        "Live Readiness": "실전 준비 상태",
        "Verified": "검증 완료",
        "Start Live Verification": "실전 검증 시작",
        "Verify Live Canary": "실전 카나리 검증",
        "Canary fills %1/%2": "카나리 체결 %1/%2",
        "Resolve Readiness Gates": "실전 준비 항목을 확인하세요",
        "Complete reconciled manual live orders up to ₩100,000 each, then verify.": "건당 10만원 이하의 수동 실전 주문을 체결·대사한 뒤 검증하세요.",
        "Live Autopilot sends real broker orders. Safety rules reduce risk but cannot prevent losses or guarantee returns.": "실전 자동매매는 실제 증권사 주문을 전송합니다. 안전 규칙은 위험을 줄이지만 손실을 막거나 수익을 보장할 수 없습니다.",
        "Live execution · expiring session · every order rechecked": "실전 주문 · 만료형 승인 세션 · 모든 주문 재검증",
        "Paper fills can differ from real market prices, latency, and partial fills. Returns are not guaranteed.": "모의 체결은 실제 시장 가격, 지연, 부분 체결과 다를 수 있습니다. 수익은 보장되지 않습니다.",
        "AI proposes candidates; deterministic safety gates recheck every live order.": "AI는 후보를 제안하고 규칙 기반 안전 게이트가 모든 실전 주문을 다시 검사합니다.",
        "Unlock production trading in Settings first.": "Settings에서 실전 주문을 먼저 허용하세요.",
        "Accept live automation risk consent in Settings first.": "Settings에서 실전 자동매매 위험 동의를 먼저 승인하세요.",
        "Complete live readiness before starting · %1/%2 passed": "실전 준비 검증을 완료하세요 · %1/%2 통과",
        "Save KIS %1 credentials and account in Settings.": "Settings에 KIS %1 API 키와 계좌를 저장하세요.",
        "Automatic Selection": "전체 자동선정",
        "AI chooses eligible candidates after every scan.": "AI가 분석할 때마다 거래 가능한 후보를 자동으로 선택합니다.",
        "Choose candidates yourself from the AI-ranked list.": "AI가 정렬한 후보 목록에서 직접 종목을 선택합니다.",
        "Analyze Candidates": "후보 분석",
        "Start Auto Trading": "자동매매 시작",
        "Stop Auto Trading": "자동매매 중지",
        "Emergency Stop": "긴급 중지",
        "AI Candidate List": "AI 후보 목록",
        "%1 selected": "%1개 선택",
        "Analyzing trends, news, and risk…": "최근 동향·뉴스·위험을 분석하는 중…",
        "Analyze candidates or press Start to scan automatically.": "후보 분석을 누르거나 자동매매를 시작하면 자동으로 분석합니다.",
        "AI %1% · Technical %2": "AI %1% · 기술 점수 %2",
        "Downside %1% · Score %2": "하락 확률 %1% · 종합 점수 %2",
        "Technical pre-screen only": "기술 지표 사전 선별만 완료",
        "One share exceeds the automatic order limit.": "1주 가격이 자동 주문 한도를 초과합니다.",
        "Safety Status": "안전 상태",
        "Environment": "환경",
        "State": "상태",
        "Selection": "종목 선택",
        "Automatic": "자동",
        "Last Analysis": "최근 분석",
        "Leading Sectors": "강세 분야",
        "Collecting market breadth": "시장 전반을 분석하는 중",
        "Research Coverage": "분석 범위",
        "%1 scanned · %2 AI analyzed": "%1개 시세 분석 · %2개 AI 분석",
        "Not yet": "아직 없음",
        "Audit Integrity": "감사 무결성",
        "Background Worker": "백그라운드 워커",
        "On": "켜짐",
        "Hard Stop": "하드 스톱",
        "Risk Per Trade": "거래당 위험",
        "Trailing Protection": "트레일링 보호",
        "Advanced Safety": "고급 안전 설정",
        "AI Autopilot is paper-only. Losses remain possible; safety gates reduce risk but cannot guarantee profit.": "AI 자동매매는 모의투자 전용입니다. 손실은 발생할 수 있으며 안전 게이트는 위험을 줄이지만 수익을 보장하지 않습니다.",
        "AI proposes candidates; deterministic safety gates authorize every paper order.": "AI는 후보를 제안하고, 규칙 기반 안전 게이트가 모든 모의주문을 승인합니다.",
        "Stopping": "중지 중",
        "Running": "실행 중",
        "Ready": "준비됨",
        "Stopped": "중지됨",
        "Error": "오류",
        "Idle": "대기",
        "Safety Halted": "안전 중지",
        "Verifying Order": "주문 확인 중",
        "Verifying Holdings": "보유자산 확인 중",
        "Action Required": "조치 필요",
        "Capital Protection": "자본 보호 중",
        "Waiting for Market": "시장 개장 대기",
        "Finding Candidates": "조건 충족 후보 탐색",
        "Retrying Protection": "보호 감시 재시도",
        "Retrying": "재시도 중",
        "Protective Exit": "보호 매도",
        "Order Submitted": "주문 접수됨",
        "Monitoring": "자동 감시 중",
        "Current Task": "현재 작업",
        "Order verification": "주문 결과 확인",
        "Broker position reconciliation": "증권사 보유자산 대조",
        "Operator action required": "사용자 조치 필요",
        "Exit-only capital protection": "신규 진입 중지·보호 매도 감시",
        "Market wait": "시장 개장 대기",
        "Scheduled monitoring": "예약된 자동 감시",
        "Candidate search": "조건 충족 후보 탐색",
        "Analysis complete": "분석 완료",
        "Protective monitoring retry": "보호 감시 재시도",
        "Market connection retry": "시장 연결 재시도",
        "Automatic check retry": "자동 점검 재시도",
        "Safety halt": "안전 중지",
        "Audit safety halt": "감사 무결성 안전 중지",
        "Account safety halt": "계좌 대조 안전 중지",
        "Live session revoked": "실전 승인 세션 해제",
        "Protective sell recheck": "보호 매도 재검증",
        "Protective sell verification": "보호 매도 결과 확인",
        "Disabled": "꺼짐",
        "Paused": "일시 정지",
        "Candidate selection": "후보 선택",
        "Technical signal": "기술 신호",
        "KIS market data": "KIS 시장 데이터",
        "Market session": "거래 가능 시간",
        "Market data freshness": "시세 최신성",
        "Market safety freshness": "시장 안전정보 최신성",
        "Tradable state": "정상 거래 상태",
        "Volatility interruption": "변동성 완화장치",
        "Daily price limit": "상·하한가 제한",
        "Instrument restrictions": "종목 거래 제한",
        "Corporate-action adjustment": "기업행사 가격 보정",
        "AI analysis": "AI 분석",
        "AI analysis freshness": "AI 분석 최신성",
        "AI confidence": "AI 신뢰도",
        "News relevance": "뉴스 관련성",
        "News evidence quality": "뉴스 근거 품질",
        "Verified company event": "검증된 기업 사건",
        "Market psychology evidence": "시장 심리 근거",
        "Market crowding risk": "시장 쏠림 위험",
        "AI agreement": "AI 모델 일치",
        "AI model confirmation": "AI 모델 교차 확인",
        "AI and technical alignment": "AI·기술 신호 일치",
        "AI downside risk": "AI 하락 위험",
        "Walk-forward validation": "워크포워드 검증",
        "Out-of-sample edge": "미사용 구간 초과성과",
        "Backtest drawdown": "백테스트 최대 낙폭",
        "Daily loss limit": "일일 손실 한도",
        "Portfolio drawdown limit": "포트폴리오 낙폭 한도",
        "Daily order limit": "일일 주문 한도",
        "Trade cooldown": "중복 거래 대기시간",
        "Sector data": "업종 데이터",
        "Sector concentration": "업종 집중도",
        "Liquidity data": "유동성 데이터",
        "Market participation": "시장 참여율",
        "Correlation data": "상관관계 데이터",
        "Portfolio correlation": "포트폴리오 상관관계",
        "Volatility data": "변동성 데이터",
        "Risk-based order size": "위험 기반 주문 수량",
        "Sellable quantity": "매도 가능 수량",
        "Portfolio risk history": "포트폴리오 위험 이력",
        "Portfolio VaR": "포트폴리오 VaR",
        "Portfolio expected shortfall": "포트폴리오 기대손실",
        "Portfolio stress test": "포트폴리오 스트레스 테스트",
        "Protective exit": "보호 매도",
        "%1 more": "외 %1개",
        "Conditions not met · %1": "미충족 조건 · %1",
        "Unmet checks · %1": "통과하지 못한 점검 · %1",
        "A safety check stopped automation. Review Advanced Safety.": "안전 점검으로 자동매매가 중지되었습니다. 고급 안전 설정에서 상세 내역을 확인하세요.",
        "Checking the final KIS order result before continuing.": "다음 거래 전에 KIS 최종 주문 결과를 확인하는 중입니다.",
        "Broker position reconciliation will retry · %1": "증권사 보유자산 대조를 다시 시도합니다 · %1",
        "Reconciling broker holdings before automatic trading continues.": "자동매매를 계속하기 전에 증권사 보유자산을 대조하는 중입니다.",
        "Action required · %1": "조치 필요 · %1",
        "Your action is required before automatic trading can continue.": "자동매매를 계속하려면 사용자 조치가 필요합니다.",
        "Waiting for broker position reconciliation": "증권사 보유자산 대조를 기다리는 중입니다.",
        "Capital protection active · %1. New entries are stopped; open positions remain monitored and may be sold automatically.": "자본 보호 작동 · %1. 신규 진입은 중지되며 보유 포지션은 계속 감시되고 필요하면 자동 매도될 수 있습니다.",
        "New entries are stopped; open positions remain monitored and may be sold automatically to limit losses.": "신규 진입은 중지되었습니다. 보유 포지션은 손실 제한을 위해 계속 감시되며 필요하면 자동 매도될 수 있습니다.",
        "New entries are halted; open positions remain under automatic loss protection": "신규 진입은 중지되었으며 보유 포지션은 자동 손실 보호 감시 중입니다.",
        "The selected market is closed. Monitoring resumes automatically at the next safety window.": "선택한 시장이 닫혀 있습니다. 다음 안전 거래 시간에 자동 감시를 재개합니다.",
        "Searching for candidates that meet every trading condition.": "모든 거래 조건을 충족하는 후보를 계속 찾는 중입니다.",
        "Protective monitoring will retry · %1": "보호 감시 재시도 예정 · %1",
        "Protective monitoring will retry automatically.": "보호 감시가 자동으로 다시 시도됩니다.",
        "Automatic check will retry · %1": "자동 점검 재시도 예정 · %1",
        "Automatic check will retry on the next cycle.": "다음 주기에 자동 점검을 다시 시도합니다.",
        "A rapid-loss rule was triggered. Rechecking the protective sell.": "급락 보호 조건이 작동했습니다. 보호 매도를 다시 확인하는 중입니다.",
        "Protective sell submitted. Verifying the final KIS result.": "보호 매도를 접수했습니다. KIS 최종 결과를 확인하는 중입니다.",
        "Order submitted. Verifying the final KIS result before the next trade.": "주문을 접수했습니다. 다음 거래 전에 KIS 최종 결과를 확인하는 중입니다.",
        "No trade · conditions not met: %1": "거래 없음 · 미충족 조건: %1",
        "No trade is needed now. Monitoring continues.": "현재 필요한 거래가 없습니다. 자동 감시를 계속합니다.",
        "Monitoring · next automatic check in %1": "자동 감시 중 · 다음 점검까지 %1",
        "Monitoring selected candidates and protective sell rules.": "선택 종목과 급락 보호 매도 조건을 감시하는 중입니다.",
        "Monitoring %1 selected candidates and protective sell rules.": "선택 종목 %1개와 급락 보호 매도 조건을 감시하는 중입니다.",
        "%1 sec": "%1초",
        "%1 min": "%1분",
        "Waiting for the next automatic check.": "다음 자동 점검을 기다리는 중입니다.",
        "KIS KRX orderbook is outside the execution freshness window": "KIS 국내 호가가 주문 허용 최신성 범위를 벗어났습니다.",
        "KIS US orderbook is outside the execution freshness window": "KIS 해외 호가가 주문 허용 최신성 범위를 벗어났습니다.",
        "Automation execution is limited to the 09:10–15:10 KST safety window": "국내 자동주문은 09:10–15:10 안전 거래 시간에만 실행됩니다.",
        "Automation execution is limited to the NASDAQ 09:40–15:50 America/New_York safety window": "NASDAQ 자동주문은 뉴욕 시간 09:40–15:50 안전 거래 시간에만 실행됩니다.",
        "Automation execution is limited to the NYSE 09:40–15:50 America/New_York safety window": "NYSE 자동주문은 뉴욕 시간 09:40–15:50 안전 거래 시간에만 실행됩니다.",
        "Select KIS Live as the data source in Settings.": "Settings에서 데이터 소스를 KIS 실시간으로 선택하세요.",
        "Switch the KIS environment to Paper.": "KIS 환경을 모의투자로 변경하세요.",
        "Save KIS paper credentials and account in Settings.": "Settings에 KIS 모의투자 API 키와 계좌를 저장하세요.",
        "Select an AI provider in Settings.": "Settings에서 AI 제공자를 선택하세요.",
        "Reset the safety kill switch in Advanced Safety before restarting.": "다시 시작하기 전에 고급 안전 설정에서 안전 킬 스위치를 재설정하세요.",
        "Select at least one AI candidate.": "AI 후보를 하나 이상 선택하세요.",
        "No candidate passed automatic selection; choose at least one candidate manually": "자동선정 기준을 통과한 후보가 없습니다. 직접 종목을 하나 이상 선택하세요.",
        "AI Autopilot was stopped while startup was in progress": "자동매매 시작 중 중지 요청이 적용되었습니다.",
        "AI Autopilot unavailable": "AI 자동매매를 사용할 수 없습니다.",
        "Emergency stop failed": "긴급 중지에 실패했습니다.",
        "Paper-only · capital preservation gates · no broker execution": "모의투자 전용 · 원금 보전 게이트 · 주문 전송 없음",
        "Paper Auto Armed": "자동 모의투자 활성",
        "Auto Paper On": "자동 모의 켜짐",
        "Enable Auto Paper": "자동 모의 켜기",
        "Confirm Auto Paper": "자동 모의 확인",
        "Auto Paper Locked": "자동 모의 잠김",
        "Promotion-gated paper automation is active · every order is rechecked before submission.": "승격 조건 기반 자동 모의투자가 활성화되었습니다 · 모든 주문은 전송 직전 다시 검증됩니다.",
        "Automatic paper execution requires explicit confirmation": "자동 모의주문을 켜려면 명시적으로 확인해야 합니다",
        "Arm KIS paper execution before enabling automatic paper orders": "자동 모의주문을 켜기 전에 KIS 모의투자를 활성화하세요",
        "Automatic paper execution is locked until every promotion gate passes": "모든 승격 조건을 통과하기 전에는 자동 모의주문이 잠겨 있습니다",
        "MODE": "모드",
        "STATE": "상태",
        "MAX ORDER": "주문 한도",
        "SHADOW RETURN": "가상 수익률",
        "FILL QUALITY": "체결 품질",
        "DECISION": "판정",
        "Dry Run": "Dry Run",
        "KIS Paper": "KIS 모의주문",
        "KIS Live": "KIS 실전주문",
        "Dry Run Armed": "Dry Run 준비됨",
        "KIS Paper Armed": "KIS 모의주문 준비됨",
        "KIS Live Armed": "KIS 실전주문 준비됨",
        "Live Auto Armed": "실전 자동매매 켜짐",
        "Kill Switch": "긴급 중지",
        "Ready · Dry Run": "통과 · Dry Run",
        "Ready · KIS Paper": "통과 · KIS 모의주문",
        "Ready · KIS Live": "통과 · KIS 실전주문",
        "Blocked": "차단됨",
        "No plan": "계획 없음",
        "Capital Protection Protocol": "원금 보전 프로토콜",
        "Paper Position Protection": "모의투자 포지션 보호",
        "Trade loss budget": "거래당 손실 예산",
        "Volatility cushion": "변동성 완충 배수",
        "Sector exposure": "업종 노출도",
        "Return correlation": "수익률 상관계수",
        "Historical VaR 95%": "과거 VaR 95%",
        "Expected shortfall 95%": "기대손실 95%",
        "Stress loss": "스트레스 손실",
        "Single-day loss": "일일 최대 손실",
        "Portfolio tail risk": "포트폴리오 꼬리위험",
        "Stress": "스트레스",
        "Market participation": "시장 참여율",
        "Bid-ask spread": "매수·매도 호가 격차",
        "Execution drift": "실행 가격 괴리",
        "Limit order timeout": "지정가 주문 대기 시간",
        "Market data age": "시세 데이터 최대 나이",
        "Plan validity": "계획 유효 시간",
        "A hard stop protects open positions. New positions are sized from a per-trade loss budget and recent volatility.": "하드 스톱으로 보유 포지션을 보호하고, 신규 포지션은 거래당 손실 예산과 최근 변동성에 맞춰 자동 조절합니다.",
        "Risk-sized cap": "위험 조정 한도",
        "Max return correlation": "최대 수익률 상관계수",
        "Volatility-adjusted loss budget allows at least one share": "변동성 조정 손실 예산으로 최소 1주 매수 가능",
        "Recent volatility evidence is available for position sizing": "포지션 크기 조정에 필요한 최근 변동성 데이터 확인",
        "Paper order would breach the volatility-adjusted loss budget": "모의주문이 변동성 조정 손실 예산을 초과합니다",
        "Every holding has sector classification data": "모든 보유 종목의 업종 분류 데이터 확인",
        "Projected sector exposure stays inside the portfolio limit": "예상 업종 노출도가 포트폴리오 한도 이내",
        "Paper order requires complete sector classification data": "모의주문에는 완전한 업종 분류 데이터가 필요합니다",
        "Paper order would breach the sector concentration limit": "모의주문이 업종 집중도 한도를 초과합니다",
        "Return correlation data is available for every holding": "모든 보유 종목의 수익률 상관관계 데이터 확인",
        "No holding exceeds the return correlation limit": "상관계수 한도를 초과하는 보유 종목 없음",
        "Portfolio holdings changed; generate a fresh automation plan": "보유 종목이 변경되었습니다. 자동화 계획을 다시 생성하세요",
        "Paper order requires complete return correlation data": "모의주문에는 완전한 수익률 상관관계 데이터가 필요합니다",
        "Paper order would breach the return correlation limit": "모의주문이 수익률 상관계수 한도를 초과합니다",
        "Portfolio tail-risk history is complete": "포트폴리오 꼬리위험 이력이 완전함",
        "Portfolio 95% historical VaR stays inside the limit": "포트폴리오 95% 과거 VaR가 한도 이내",
        "Portfolio expected shortfall stays inside the limit": "포트폴리오 기대손실이 한도 이내",
        "Portfolio stress and single-day loss stay inside the limits": "포트폴리오 스트레스 및 일일 손실이 한도 이내",
        "Paper order requires complete portfolio tail-risk history": "모의주문에는 완전한 포트폴리오 꼬리위험 이력이 필요합니다",
        "Paper order would breach portfolio tail-risk limits": "모의주문이 포트폴리오 꼬리위험 한도를 초과합니다",
        "Recent market turnover is available for liquidity sizing": "유동성 조정에 필요한 최근 거래대금 확인",
        "Order size stays below the market participation limit": "주문 규모가 시장 참여율 한도 이내",
        "Paper order requires complete liquidity data": "모의주문에는 완전한 유동성 데이터가 필요합니다",
        "Paper order would breach the market participation limit": "모의주문이 시장 참여율 한도를 초과합니다",
        "Paper order requires a valid KIS bid-ask quote": "모의주문에는 유효한 KIS 매수·매도 호가가 필요합니다",
        "Paper order would breach the bid-ask spread limit": "모의주문이 매수·매도 호가 격차 한도를 초과합니다",
        "Market data is inside the freshness window": "시세 데이터가 허용된 최신 구간 이내",
        "KIS quote is outside the execution freshness window": "KIS 시세가 주문 실행 신선도 범위를 벗어났습니다",
        "The security is in a normal tradable state": "종목이 정상 거래 가능 상태",
        "Market safety status is inside the freshness window": "거래 안전 상태가 허용된 최신 구간 이내",
        "No volatility interruption is active": "현재 발동 중인 변동성 완화장치(VI) 없음",
        "The price is away from its daily limits": "주가가 일일 상·하한가에서 벗어나 있음",
        "No caution, warning, managed, overheated, or liquidation flag is active": "투자주의·경고·관리·단기과열·정리매매 지정 없음",
        "Historical prices are adjusted for corporate actions": "기업행사를 반영한 수정주가 이력 사용",
        "KIS reports that the security is not in a normal tradable state": "KIS에서 해당 종목을 정상 거래 가능 상태로 확인할 수 없습니다",
        "KIS volatility interruption status is unavailable": "KIS 변동성 완화장치 상태를 확인할 수 없습니다",
        "A volatility interruption is active; paper order blocked": "변동성 완화장치가 발동되어 모의주문을 차단했습니다",
        "KIS risk flags block new automated exposure": "KIS 위험 지정으로 신규 자동 매수를 차단했습니다",
        "Paper buy order is blocked at the daily upper price limit": "일일 상한가에서 자동 모의매수를 차단했습니다",
        "Paper sell order is blocked at the daily lower price limit": "일일 하한가에서 자동 모의매도를 차단했습니다",
        "Stale limit order cancellation requested": "대기 시간을 넘긴 지정가 주문의 취소를 요청했습니다",
        "Stale limit order cancellation outcome is uncertain; automation was halted": "지정가 주문 취소 결과가 불확실하여 자동화를 긴급 중지했습니다",
        "memory-semiconductors": "메모리 반도체",
        "logic-semiconductors": "시스템 반도체",
        "ai-infrastructure": "AI 인프라",
        "internet-platform": "인터넷 플랫폼",
        "cloud-software": "클라우드 소프트웨어",
        "digital-content": "디지털 콘텐츠",
        "fintech-payments": "핀테크·결제",
        "mobility": "모빌리티",
        "battery-materials": "배터리·소재",
        "biotech": "바이오",
        "finance": "금융",
        "energy-industrial": "에너지·산업재",
        "consumer-electronics": "소비자 전자",
        "ecommerce-retail": "이커머스·유통",
        "social-advertising": "소셜·광고",
        "telecom": "통신",
        "Operational Alerts": "운영 알림",
        "Paper orders, protective exits, and safety failures": "모의주문·보호 매도·안전성 오류를 알립니다",
        "OPERATIONS": "운영 상태",
        "Audit Failure": "감사 무결성 오류",
        "Reconcile Required": "회계 대사 필요",
        "Self-Test Due": "복구 시험 필요",
        "System Test Due": "시스템 시험 필요",
        "Run System Test": "시스템 시험",
        "Online Validation Failure": "온라인 검증 오류",
        "Soak Halted": "장기 검증 중지",
        "Online Test Due": "온라인 검증 필요",
        "Soak %1%": "장기 검증 %1%",
        "Live Canary": "실전 카나리",
        "Start Soak": "장기 검증 시작",
        "Resume Soak": "장기 검증 재개",
        "Pause Soak": "장기 검증 일시정지",
        "Validated": "검증 완료",
        "Accounting state checksum is valid": "회계 상태 체크섬이 유효함",
        "Broker positions have an accounting baseline": "증권사 포지션 회계 기준점이 생성됨",
        "Expected and broker holding quantities reconcile": "예상 수량과 증권사 보유 수량이 일치함",
        "Five consecutive accounting reconciliations have passed": "회계 대사를 5회 연속 통과함",
        "Atomic durable state replacement succeeds": "원자적 상태 저장 시험 통과",
        "Exclusive process lock succeeds": "프로세스 배타 잠금 시험 통과",
        "Checksum detects modified records": "체크섬 변조 탐지 시험 통과",
        "Duplicate execution keys are rejected": "중복 주문 키 차단 시험 통과",
        "Malformed journal records are detected": "손상된 기록 탐지 시험 통과",
        "Current automation journals pass integrity verification": "현재 자동화 기록 무결성 검증 통과",
        "Resilience-test result checksum is valid": "복구 시험 결과 체크섬이 유효함",
        "Resilience test was run within seven days": "최근 7일 이내 복구 시험을 완료함",
        "Every shadow and paper promotion gate passes": "가상 및 모의투자 승격 조건을 모두 통과함",
        "Paper holdings pass repeated accounting reconciliation": "모의 보유 수량이 반복 회계 대사를 통과함",
        "Recent failure-recovery validation passes": "최근 장애 복구 검증을 통과함",
        "KIS production API credentials are stored": "KIS 실전 API 인증 정보가 저장됨",
        "KIS production account is stored": "KIS 실전 계좌가 저장됨",
        "Production trading is explicitly unlocked in the global risk policy": "전역 위험 정책에서 실전투자를 명시적으로 허용함",
        "No automation execution outcome is uncertain": "결과가 불확실한 자동 주문이 없음",
        "All automation journals pass integrity verification": "모든 자동화 기록 무결성 검증 통과",
        "Live-readiness state checksum is valid": "실전 준비 상태 체크섬이 유효함",
        "Reconciled manual live canary fills are sufficient": "대사 완료된 수동 실전 카나리 체결이 충분함",
        "Automation journals and position state are intact": "자동화 기록과 포지션 상태가 온전함",
        "No order requires broker reconciliation": "증권사 대사가 필요한 주문이 없음",
        "Automation policy state is internally consistent": "자동화 정책 상태가 내부적으로 일관됨",
        "The local failure-recovery suite is current": "로컬 장애 복구 시험이 최신 상태",
        "A verified automation rollback snapshot is available": "검증된 자동화 롤백 스냅샷이 있음",
        "Automation state is private to the current user": "자동화 상태 파일이 현재 사용자에게만 공개됨",
        "State storage has at least 100 MB free": "상태 저장 공간이 100MB 이상 남아 있음",
        "No interrupted automation state write is stale": "중단된 오래된 자동화 상태 쓰기가 없음",
        "Operational incident history is intact": "운영 장애 이력의 무결성이 정상임",
        "The scheduler has no consecutive failures": "스케줄러에 연속 장애가 없음",
        "The required background worker heartbeat is healthy": "필요한 백그라운드 워커 하트비트가 정상임",
        "A concurrent writer cannot enter the critical section": "동시 쓰기 프로세스의 임계 구역 진입이 차단됨",
        "An interrupted replacement preserves the last durable state": "중단된 파일 교체에서도 마지막 정상 상태가 보존됨",
        "Journal deletion and chain rewrites are detected": "기록 삭제와 체인 변조를 탐지함",
        "Local operational-hardening checks pass": "로컬 운영 안정성 강화 검사를 통과함",
        "Online-validation evidence checksum is valid": "온라인 검증 증거 체크섬이 유효함",
        "KIS paper online validation has started": "KIS 모의투자 온라인 검증이 시작됨",
        "Background worker is active for online validation": "온라인 검증 백그라운드 워커가 실행 중",
        "The required worker-cycle sample is recorded": "필요한 워커 실행 표본이 누적됨",
        "The required KIS paper observation sample is recorded": "필요한 KIS 모의투자 관찰 표본이 누적됨",
        "Sixty healthy market sessions are recorded": "정상 시장 세션 60일이 누적됨",
        "Recent worker success rate stays at or above 99%": "최근 워커 성공률이 99% 이상 유지됨",
        "Recent KIS paper success rate stays at or above 99%": "최근 KIS 모의투자 성공률이 99% 이상 유지됨",
        "No KIS rate-limit event occurred in the recent SLO window": "최근 SLO 구간에 KIS 호출 제한이 발생하지 않음",
        "Worker p95 duration stays below 60 seconds": "워커 p95 실행 시간이 60초 미만으로 유지됨",
        "Online validation has no active failure-budget halt": "온라인 검증 오류 예산으로 인한 중지가 없음",
        "Local operational-hardening checks remain healthy": "로컬 운영 안정성 검사가 계속 정상임",
        "Order outcomes and automation journals remain certain": "주문 결과와 자동화 기록의 불확실성이 없음",
        "Repeated paper-account reconciliation remains healthy": "반복 모의계좌 대사가 계속 정상임",
        "Shadow and paper promotion evidence passes every gate": "가상·모의투자 승격 증거가 모든 조건을 통과함",
        "Live-canary readiness state checksum is valid": "실전 카나리 준비 상태 체크섬이 유효함",
        "Manual live canary fills are reconciled without uncertainty": "수동 실전 카나리 체결이 불확실성 없이 대사됨",
        "Manual live canary evidence is explicitly verified": "수동 실전 카나리 증거가 명시적으로 검증됨",
        "KIS paper online validation passes every operational SLO": "KIS 모의투자 온라인 검증이 모든 운영 SLO를 통과함",
        "Worker Off": "백그라운드 꺼짐",
        "Worker Stale": "백그라운드 지연",
        "Alerts Off": "알림 꺼짐",
        "Healthy": "정상",
        "Checking…": "확인 중…",
        "Paper Only · Global": "모의투자 전용 · 전체 적용",
        "A hard stop exits a losing position. Trailing protection activates after a gain, then exits after the configured drop from its peak.": "하드 스톱은 손실 포지션을 매도합니다. 트레일링 보호는 설정한 수익률에 도달한 뒤 최고가에서 지정한 만큼 하락하면 매도합니다.",
        "Hard stop": "하드 스톱",
        "Trail starts": "트레일링 시작",
        "Peak drop": "최고가 대비 하락",
        "Reset Defaults": "기본값 복원",
        "Paper protection settings saved": "모의투자 보호 설정을 저장했습니다",
        "Saving paper protection settings…": "모의투자 보호 설정 저장 중…",
        "Automation policy unavailable": "자동화 정책을 불러올 수 없습니다",
        "Hard stop %1% · trailing starts +%2% · exits %3% below peak.": "하드 스톱 %1% · +%2%부터 트레일링 · 최고가 대비 %3% 하락 시 매도",
        "Preserve capital first. Missing evidence, model conflict, loss limits, or duplicate signals always block the plan.": "원금 보전을 최우선으로 합니다. 근거 누락, 모델 충돌, 손실 한도 도달 또는 중복 신호가 있으면 항상 계획을 차단합니다.",
        "This stage cannot send broker orders. It records hypothetical paper plans only.": "현재 단계에서는 증권사 주문을 보낼 수 없으며 가상의 모의투자 계획만 기록합니다.",
        "Dry Run records hypothetical plans and never contacts the broker order endpoint.": "Dry Run은 가상 계획만 기록하며 증권사 주문 API를 호출하지 않습니다.",
        "Observer checks the selected target every %1 minutes when Background Monitoring is on; it never executes orders.": "백그라운드 모니터링이 켜져 있으면 관찰기가 선택 종목을 %1분마다 점검하며 주문은 절대 실행하지 않습니다.",
        "Observer checks every %1 minutes · promotion %2/%3 · automatic execution locked.": "관찰 주기 %1분 · 승격 조건 %2/%3 · 자동 주문 잠김",
        "Only explicitly confirmed KIS paper orders can be sent. Production remains hard-locked.": "명시적으로 확인한 KIS 모의주문만 전송할 수 있으며 실전 주문은 계속 강제 차단됩니다.",
        "Only explicitly armed KIS orders can be sent. Live sessions expire automatically and every order is rechecked.": "명시적으로 승인한 KIS 주문만 전송됩니다. 실전 세션은 자동 만료되며 모든 주문을 다시 검사합니다.",
        "KIS paper execution · serial reconciliation · production hard-locked": "KIS 모의주문 · 순차 체결 대조 · 실전 주문 강제 차단",
        "KIS live execution · expiring authorization · serial reconciliation": "KIS 실전주문 · 만료형 승인 · 순차 체결 대조",
        "Reset Kill Switch": "긴급 중지 해제",
        "Pause": "일시 정지",
        "Arm Dry Run": "Dry Run 준비",
        "Arm KIS Paper": "KIS 모의주문 준비",
        "Arm KIS Live": "KIS 실전주문 준비",
        "Live Automation Consent": "실계좌 자동매매 리스크 동의",
        "Real-money automation can lose capital. Arming still requires every verification gate.": "실제 자금 자동매매는 손실이 발생할 수 있습니다. 준비(무장)하려면 모든 검증 게이트를 통과해야 합니다.",
        "Live Armed · Gated": "실전 무장됨 · 게이트 적용",
        "Live Consent · Gated": "실전 동의됨 · 게이트 적용",
        "Enable Observer": "관찰기 켜기",
        "Observer On": "관찰기 켜짐",
        "Observe This Stock": "이 종목 관찰",
        "Target Selected": "관찰 종목 선택됨",
        "Verify Operations": "운영 검증",
        "Guarded Order Plan": "보호된 주문 계획",
        "today": "오늘",
        "Action": "동작",
        "Notional": "주문 금액",
        "Technical Score": "기술 점수",
        "AI Confidence": "AI 신뢰도",
        "OOS Return": "표본 외 수익률",
        "Portfolio Drawdown": "포트폴리오 낙폭",
        "Evaluating…": "평가 중…",
        "Generate Dry Run Plan": "Dry Run 계획 생성",
        "Generate Paper Plan": "모의주문 계획 생성",
        "Execute Paper Plan": "모의주문 실행",
        "Confirm Paper Order": "모의주문 확인",
        "Plan Executed": "실행 완료",
        "Reconcile KIS": "KIS 체결 대조",
        "Ready for explicit KIS paper confirmation": "KIS 모의주문 확인 준비 완료",
        "KIS paper order accepted; reconciliation is required before another execution": "KIS 모의주문 접수 완료 · 다음 주문 전에 체결 대조가 필요합니다",
        "No broker order sent": "증권사에 전송된 주문 없음",
        "Generate a plan to evaluate every safety gate.": "계획을 생성하여 모든 안전 게이트를 평가하세요.",
        "Safety Gates": "안전 게이트",
        "Safety & Promotion Gates": "안전 및 승격 게이트",
        "%1/%2 passed": "%1/%2 통과",
        "No safety evaluation yet.": "아직 안전성 평가가 없습니다.",
        "Paper account only": "모의투자 계좌만 허용",
        "No broker order can be sent": "증권사 주문 전송 불가",
        "Dry Run records a hypothetical plan": "Dry Run 가상 계획만 기록",
        "KIS paper execution is explicitly armed": "KIS 모의주문이 명시적으로 준비됨",
        "Live KIS paper data is required for execution": "주문 실행에 KIS 모의투자 실시간 데이터가 필요함",
        "Dry Run automation is armed": "Dry Run 자동화 준비 완료",
        "KIS paper automation is armed": "KIS 모의주문 자동화 준비 완료",
        "Technical score clears the abstention band": "기술 점수가 관망 구간을 벗어남",
        "Fresh AI scenario is available": "AI 시나리오 사용 가능",
        "AI scenario is inside the freshness window": "AI 시나리오가 최신 상태임",
        "AI confidence clears the quality floor": "AI 신뢰도가 최소 기준을 통과함",
        "AI providers do not conflict": "AI 모델 간 직접 충돌 없음",
        "Two-model confirmation is present": "두 개 모델의 확인을 확보함",
        "Technical and AI directions agree": "기술 신호와 AI 방향이 일치함",
        "AI downside probability stays below the buy limit": "AI 하락 확률이 매수 제한 기준 이하임",
        "Walk-forward validation is robust": "워크포워드 검증 결과가 견고함",
        "Out-of-sample return and excess return are positive": "표본 외 수익률과 초과 수익률이 모두 양수임",
        "Backtest drawdown stays inside the research limit": "백테스트 낙폭이 연구 한도 이내임",
        "Daily loss circuit breaker is clear": "일일 손실 차단 기준을 넘지 않음",
        "Portfolio drawdown circuit breaker is clear": "포트폴리오 낙폭 차단 기준을 넘지 않음",
        "Daily plan count is below the limit": "일일 계획 횟수가 한도 미만임",
        "Duplicate-side cooldown has elapsed": "동일 방향 중복 방지 시간이 지남",
        "Capital-preserving position size is at least one share": "원금 보전 기준 주문 가능 수량이 1주 이상임",
        "A sellable paper position exists": "매도 가능한 모의투자 보유 수량이 있음",
        "Position loss protection requires a full paper exit": "포지션 손실 보호 기준에 따라 모의 보유 수량 전량 매도가 필요함",
        "Shadow observation sample is sufficient": "가상 관찰 표본 수가 충분함",
        "Shadow test spans enough trading sessions": "가상 검증 기간이 충분한 거래일을 포함함",
        "Closed shadow trade sample is sufficient": "종료된 가상 거래 표본 수가 충분함",
        "Cost-adjusted shadow return is positive": "비용 반영 가상 수익률이 양수임",
        "Shadow portfolio beats its observed benchmark": "가상 포트폴리오가 관찰 벤치마크를 초과함",
        "Shadow drawdown stays inside the promotion limit": "가상 포트폴리오 낙폭이 승격 한도 이내임",
        "Shadow profit factor clears the promotion floor": "가상 손익비가 승격 기준을 통과함",
        "Shadow win rate clears the promotion floor": "가상 승률이 승격 기준을 통과함",
        "Manual KIS paper fills are sufficient": "수동 KIS 모의 체결 표본 수가 충분함",
        "Paper order fill rate clears the promotion floor": "모의주문 체결률이 승격 기준을 통과함",
        "Paper execution slippage stays inside the promotion limits": "모의주문 체결 슬리피지가 승격 한도 이내임",
        "No paper execution is unresolved": "미확정 모의주문이 없음",
        "Automation plans and execution journals pass integrity verification": "자동화 계획과 주문 기록의 무결성 검증을 통과함",
        "Observer has no consecutive operational failures": "관찰기에 연속 운영 장애가 없음",
        "Automation currently supports KRX symbols only": "자동화는 현재 국내 종목만 지원합니다",
        "Automation is hard-locked to paper accounts": "자동화는 모의투자 계좌로 강제 제한되어 있습니다",
        "A current positive price is required": "유효한 현재 가격이 필요합니다",
        "Account evaluation is unavailable": "계좌 평가금액을 확인할 수 없습니다",
        "Automation plan expired; generate a fresh plan": "자동화 계획이 만료되었습니다. 새 계획을 생성하세요",
        "Protective paper exit accepted; automation was halted pending reconciliation": "보호 매도 주문이 접수되었습니다. 체결 확인 전까지 자동화를 중단했습니다",
        "An earlier paper order is unresolved; reconcile before continuing": "이전 모의주문 상태가 미확정입니다. 계속하기 전에 KIS 체결 대조를 실행하세요",
        "Paper execution is limited to the 09:10–15:10 KST safety window": "모의주문은 안전 구간인 09:10–15:10에만 실행됩니다",
        "Price moved beyond the execution drift limit; generate a fresh plan": "가격이 실행 허용 범위를 벗어났습니다. 새 계획을 생성하세요",
        "Paper order outcome is uncertain. Automation was halted; reconcile with KIS before continuing": "모의주문 결과가 불확실하여 자동화를 긴급 중지했습니다. 계속하기 전에 KIS에서 체결 상태를 대조하세요",
        "Low overfit risk": "과최적화 위험 낮음",
        "High overfit risk": "과최적화 위험 높음",
        "Moderate risk": "과최적화 위험 보통",
        "Open": "평가 대기",
        "Correct": "적중",
        "Miss": "빗나감",
        "%1 close": "%1 종가",
        "%1 est.": "%1 예정",
        "Bullish": "상승 우세",
        "Bearish": "하락 우세",
        "Neutral": "중립",
        "Awaiting": "분석 대기",
        "Local preview only": "로컬 미리보기만 실행",
        "Production orders are locked": "실전 주문이 잠겨 있습니다",
        "Save KIS %1 API credentials in Settings": "Settings에서 KIS %1 API 인증 정보를 저장하세요",
        "Save the %1 account number in Settings": "Settings에서 %1 계좌번호를 저장하세요",
        "Checking account…": "계좌 확인 중…",
        "Account data required": "계좌 정보가 필요합니다",
        "Exceeds available buy quantity": "매수 가능 수량을 초과했습니다",
        "Exceeds sellable holdings": "매도 가능 보유 수량을 초과했습니다",
        "KIS production order · LIVE confirmation required": "KIS 실전 주문 · LIVE 확인 필요",
        "KIS paper order": "KIS 모의투자 주문",
        "Checking account and risk policy…": "계좌와 위험 제한 확인 중…",
        "Waiting for server checks…": "서버 확인 대기 중…",
        "Local preview only · no broker order will be sent": "로컬 미리보기만 실행 · 증권사에 주문을 보내지 않음",
        "KIS paper account checks passed · rechecked at submit": "KIS 모의투자 계좌 확인 완료 · 제출 시 다시 확인",
        "Risk Guard passed · daily buys %1/%2 · rechecked at submit": "위험 제한 통과 · 일일 매수 %1/%2회 · 제출 시 다시 확인",
        "Risk Guard passed · all limits are rechecked at submit": "위험 제한 통과 · 제출 시 모든 한도를 다시 확인",
        "%1 %2 shares of %3 · Local preview complete": "%3 · %1 %2주 · 로컬 미리보기 완료",
        "TOTAL": "총자산",
        "CASH": "예수금",
        "STOCKS": "주식 평가액",
        "P&L": "평가 손익",
        "Updating…": "업데이트 중…",
        "Loading local activity…": "로컬 거래 기록을 불러오는 중…",
        "No local trade activity yet.": "아직 로컬 거래 기록이 없습니다.",
        "Paper Portfolio": "모의투자 보유 자산",
        "Production Portfolio": "실전투자 보유 자산",
        "%1 holdings": "보유 종목 %1개",
        "%1 · %2 shares · Avg %3": "%1 · %2주 · 평균 %3",
        "Loading portfolio…": "보유 자산을 불러오는 중…",
        "No holdings in this account.": "이 계좌에 보유 종목이 없습니다.",
        "Paper Orders": "모의투자 주문",
        "%1 cancelable": "취소 가능 %1건",
        "Loading recent orders…": "최근 주문을 불러오는 중…",
        "No recent orders for this symbol.": "이 종목의 최근 주문이 없습니다.",
        "Sell %1 %2": "%2 %1주 매도",
        "Buy %1 %2": "%2 %1주 매수",
        "Type LIVE to cancel the unfilled quantity in your production account.": "실전 계좌의 미체결 수량을 취소하려면 LIVE를 입력하세요.",
        "Only the unfilled quantity will be canceled in your KIS mock account.": "KIS 모의투자 계좌의 미체결 수량만 취소됩니다.",
        "Canceling…": "취소 중…",
        "Cancel Remaining": "미체결 취소",
        "Review Local Preview": "로컬 미리보기 확인",
        "Review Production Order": "실전 주문 확인",
        "Review KIS Paper Order": "KIS 모의투자 주문 확인",
        "Buy %1 %2 at %3": "%2 %1주 매수 · %3",
        "Sell %1 %2 at %3": "%2 %1주 매도 · %3",
        "market price": "시장가",
        "%1 shares": "%1주",
        "Submitting…": "제출 중…",
        "Confirm Preview": "미리보기 확인",
        "Place Live Order": "실전 주문 제출",
        "Confirm Paper": "모의투자 확인",
        "Review KIS Paper": "KIS 모의투자 확인",
        "Review Live Order": "실전 주문 확인",
        "Production Locked": "실전 주문 잠김",
        "Review Preview": "미리보기 확인",
        "KIS Production · Orders locked": "KIS 실전투자 · 주문 잠김",
        "Buyable %1 · %2": "매수 가능 %1주 · %2",
        "Sellable %1 shares": "매도 가능 %1주",
        "Buying power %1": "매수 가능 금액 %1",
        "Cached": "캐시됨",
        "Orders · %1": "주문 · %1건",
        "Orders": "주문",
        "KIS WebSocket · Live": "KIS WebSocket · 실시간",
        "KIS REST · %1": "KIS REST · %1",
        "Polling": "주기적 갱신",
        "Paper market data": "모의 시장 데이터",
        "LOW": "저가",
        "HIGH": "고가",
        "VOLUME": "거래량",
        "Watchlist": "관심종목",
        "Price Alerts": "가격 알림",
        "Alerts %1": "알림 %1개",
        "Above": "상향 돌파",
        "Below": "하향 이탈",
        "Add Alert": "알림 추가",
        "No price alerts yet.": "등록된 가격 알림이 없습니다.",
        "%1 completed provider calls in the last 30 days": "최근 30일간 완료된 AI 제공자 호출 %1회",
        "%1 in · %2 out": "입력 %1 · 출력 %2",
        "%1 of %2 symbols screened · select a row to inspect": "종목 %2개 중 %1개 분석 · 행을 선택해 상세 보기",
        "%1 of 16 alerts": "알림 %1개 / 16개",
        "%1 symbols": "관심종목 %1개",
        "%1 resolved forecasts · %2 model predictions": "평가 완료 예측 %1개 · 모델 예측 %2개",
        "%1 results": "결과 %1개",
        "%1 total": "합계 %1",
        "%1 · %2 calls": "%1 · %2회 호출",
        "%1 · %2 tokens": "%1 · 토큰 %2개",
        "%1% actual · n%2": "실제 %1% · 표본 %2개",
        "%1pp": "%1%p",
        "Add": "추가",
        "Add symbols to the watchlist, then refresh the screener.": "관심종목에 종목을 추가한 뒤 스크리너를 새로고침하세요.",
        "Add the current symbol to start a watchlist.": "현재 종목을 추가해 관심종목 목록을 시작하세요.",
        "Added": "추가됨",
        "Armed": "알림 준비됨",
        "Loading model history…": "모델 이력 불러오는 중…",
        "Loading watchlist…": "관심종목 불러오는 중…",
        "Loading…": "불러오는 중…",
        "Local metadata only · provider billing dashboards remain the source of truth for cost.": "로컬 메타데이터만 표시 · 비용은 제공자 결제 대시보드를 기준으로 확인하세요.",
        "No matching symbols.": "일치하는 종목이 없습니다.",
        "No recent calls": "최근 호출이 없습니다",
        "No recorded API usage": "기록된 API 사용량이 없습니다",
        "No resolved model predictions yet.": "아직 평가 완료된 모델 예측이 없습니다.",
        "No watchlist symbols to screen.": "분석할 관심종목이 없습니다.",
        "Pause": "일시 정지",
        "Paused": "일시 정지됨",
        "Quote error": "시세 조회 오류",
        "RSI": "RSI",
        "Ranking the watchlist from completed daily closes…": "완료된 일봉 종가를 바탕으로 관심종목 순위를 계산하는 중…",
        "Reading the local token ledger…": "로컬 토큰 사용 기록을 읽는 중…",
        "Recalculating calibration and qualified metrics…": "신뢰도 보정과 유효 성과 지표를 다시 계산하는 중…",
        "Resolved forecasts are required before calibration becomes measurable.": "보정을 측정하려면 평가 완료된 예측이 필요합니다.",
        "Resume": "다시 시작",
        "Screening unavailable": "스크리너를 사용할 수 없습니다",
        "Screening watchlist…": "관심종목 분석 중…",
        "Search Korean stocks": "국내 종목 검색",
        "Search name or symbol": "종목명 또는 종목 코드 검색",
        "Searching symbols…": "종목 검색 중…",
        "Searching…": "검색 중…",
        "Signal agreement is descriptive, not causal attribution, and never authorizes an order.": "신호 일치도는 설명용 지표일 뿐 인과관계를 의미하지 않으며 주문을 승인하지 않습니다.",
        "Target price": "목표 가격",
        "Target · %1": "목표 · %1",
        "Trend + momentum + RSI ranking from completed closes · not investment advice or an order signal.": "완료된 종가 기반 추세 + 모멘텀 + RSI 순위 · 투자 조언이나 주문 신호가 아닙니다.",
        "Triggered · waiting to re-arm": "알림 발생 · 재활성화 대기 중",
        "Unavailable": "조회 불가",
        "Unknown model": "알 수 없는 모델",
        "usable": "사용 가능",
        "limited": "표본 부족",
        "unavailable": "사용 불가",
        "Updating quotes…": "시세 업데이트 중…",
        "Waiting for recross": "가격 재교차 대기 중",
        "Already in your watchlist.": "이미 관심종목에 있습니다.",
        "Remove this symbol's price alerts first.": "이 종목의 가격 알림을 먼저 삭제하세요.",
        "Enter a valid target price.": "올바른 목표 가격을 입력하세요.",
        "Price alerts are limited to 16.": "가격 알림은 최대 16개까지 추가할 수 있습니다.",
        "That price alert already exists.": "동일한 가격 알림이 이미 있습니다.",
        "Quant Lab": "퀀트 분석",
        "Forecasts": "예측 기록",
        "Backtest": "과거 성과 검증",
        "Compare": "전략 비교",
        "AI Eval": "AI 검증",
        "Usage": "API 사용량",
        "Screener": "종목 선별",
        "Details": "상세",
        "Scenario": "전망",
        "Confidence": "신뢰도",
        "Walk-forward": "순차 표본 외 검증",
        "QUALIFIED HIT": "유효 예측 적중률",
        "QUALIFIED / RESOLVED": "유효 / 평가 완료",
        "OPEN": "평가 대기",
        "BRIER · LOWER BETTER": "예측 확률 오차 · 낮을수록 좋음",
        "AI Scenario Report": "AI 시나리오 분석",
        "SCENARIO": "전망",
        "CONFIDENCE": "신뢰도",
        "UP / FLAT / DOWN": "상승 / 보합 / 하락",
        "SOURCES": "분석 출처",
        "Summary": "요약",
        "Provider Status": "AI 제공자 상태",
        "Token Usage": "토큰 사용량",
        "Historical Confidence Calibration": "과거 신뢰도 보정",
        "Ensemble Agreement": "모델 합의도",
        "Historical Model Weighting": "과거 성과 기반 모델 가중치",
        "Chart Signal": "차트 신호",
        "News Signal": "뉴스 신호",
        "News Evidence Quality": "뉴스 근거 품질",
        "Chart Metrics": "차트 지표",
        "20D RETURN": "20일 수익률",
        "MA SPREAD": "이동평균선 간격",
        "20D ANN VOL": "20일 연환산 변동성",
        "RSI 14": "RSI 14",
        "60D RETURN": "60일 수익률",
        "PRICE / MA60": "현재가 / 60일선",
        "60D DRAWDOWN": "60일 최대 낙폭",
        "TREND REGIME": "추세 국면",
        "Walk-forward Evidence": "순차 표본 외 검증 근거",
        "HIT RATE": "적중률",
        "SAMPLES": "표본 수",
        "TEST RETURN": "검증 수익률",
        "MAX DRAWDOWN": "최대 낙폭",
        "Catalysts": "상승 촉매",
        "Risks": "주요 위험",
        "Recent News Evidence": "최근 뉴스 근거",
        "No recent headlines were available.": "최근 뉴스 제목을 가져오지 못했습니다.",
        "Trend": "추세",
        "Momentum": "모멘텀",
        "Ideal": "이상적",
        "Base": "기본",
        "Stress": "비용 악화",
        "STRATEGY": "전략 수익률",
        "BUY & HOLD": "단순 보유",
        "EXCESS": "초과 수익률",
        "WF OOS RETURN": "표본 외 수익률",
        "WF OOS EXCESS": "표본 외 초과 수익률",
        "FOLD WINS": "구간 우위",
        "WF SHARPE": "표본 외 샤프 지수",
        "Strategy": "전략",
        "Buy & Hold": "단순 보유",
        "Same adjusted closes · same execution costs": "동일한 수정주가 · 동일한 거래 비용",
        "BEST OOS BALANCE": "최고 표본 외 균형",
        "ROBUSTNESS": "견고성",
        "HIGH OVERFIT RISK": "높은 과최적화 위험",
        "STRATEGIES": "전략 수",
        "Inspect": "상세 보기",
        "OOS": "표본 외",
        "FOLDS": "검증 구간",
        "OOS MDD": "표본 외 최대 낙폭",
        "P/L FACTOR": "수익계수",
        "SWITCH/YR": "연간 매매 전환",
        "SCREENED": "분석 종목",
        "BULLISH": "상승 우세",
        "NEUTRAL": "중립",
        "BEARISH": "하락 우세",
        "20D": "20일",
        "VOL": "변동성",
        "DD 60D": "60일 낙폭",
        "API CALLS": "API 호출",
        "BILLABLE INPUT": "과금 입력 토큰",
        "OUTPUT": "출력 토큰",
        "TOTAL TOKENS": "전체 토큰",
        "MODEL USAGE": "모델별 사용량",
        "RECENT CALLS": "최근 호출",
        "Qualified confidence floor": "유효 예측 최소 신뢰도",
        "Lower-confidence predictions remain journaled but are excluded from qualified metrics.": "기준보다 신뢰도가 낮은 예측도 기록되지만 유효 성과 지표에서는 제외됩니다.",
        "QUALIFIED HIT RATE": "유효 예측 적중률",
        "QUALIFIED BRIER": "유효 예측 확률 오차",
        "CALIBRATION ECE": "보정 오차(ECE)",
        "QUALIFIED / EXCLUDED": "유효 / 제외",
        "Chart direction agreement": "차트 방향 일치도",
        "News direction agreement": "뉴스 방향 일치도",
        "MODEL PERFORMANCE · RESOLVED PREDICTIONS": "모델 성과 · 평가 완료 예측",
        "QUAL HIT": "유효 적중률",
        "BRIER": "확률 오차",
        "CAL GAP": "보정 오차",
        "N / EXCL": "표본 / 제외",
        "QUALITY": "품질",
        "CONFIDENCE 0–49": "신뢰도 0–49",
        "CONFIDENCE 50–69": "신뢰도 50–69",
        "CONFIDENCE 70–100": "신뢰도 70–100",
        "QUAL COVER": "유효 포함률",
        "AVG CONF": "평균 신뢰도",
        " · %1 · %2 sessions": " · %1 · %2거래일",
        " · Calibrated": " · 보정됨",
        " · Journaled": " · 기록됨",
        " · Low confidence": " · 낮은 신뢰도",
        " · Model conflict": " · 모델 판단 충돌",
        " · Partial provider result": " · 일부 제공자 결과",
        " · Weighted ensemble": " · 가중 앙상블",
        " · bullish/bearish conflict": " · 상승·하락 판단 충돌",
        " · cached %1": " · 캐시 %1",
        " · hit %1%": " · 적중률 %1%",
        " · low confidence": " · 낮은 신뢰도",
        " · reasoning %1": " · 추론 %1",
        "%1  Models: %2": "%1  모델: %2",
        "%1 %2": "%1 %2",
        "%1 %2 %3": "%1 %2 %3",
        "%1 %2% · n%3": "%1 %2% · 표본 %3개",
        "%1 API calls · input %2 · output %3 · total %4": "API 호출 %1회 · 입력 %2 · 출력 %3 · 합계 %4",
        "%1 agreement · score %2/100 · probability disagreement %3pp · confidence %4% → %5%": "%1 합의 · 점수 %2/100 · 확률 차이 %3%p · 신뢰도 %4% → %5%",
        "%1 news · %2 sources": "뉴스 %1건 · 출처 %2곳",
        "%1 unavailable · %2": "%1 사용 불가 · %2",
        "%1 · %2": "%1 · %2",
        "%1 · %2%3": "%1 · %2%3",
        "%1 · %2—%3 · %4 sessions · %5/%6/%7 bps commission/slippage/tax": "%1 · %2—%3 · %4거래일 · 수수료/슬리피지/매도세 %5/%6/%7bp",
        "%1 · 5 trading-day checks · local journal": "%1 · 5거래일 검증 · 로컬 기록",
        "%1 · daily close simulation · no look-ahead": "%1 · 일봉 종가 시뮬레이션 · 미래 데이터 미사용",
        "%1 · identical data and costs · OOS ranking": "%1 · 동일 데이터·비용 · 표본 외 순위",
        "%1 · model calibration · confidence quality gate": "%1 · 모델 보정 · 신뢰도 품질 기준",
        "%1 · quality %2/100 · %3 unique headlines · %4 sources · %5 within 24h · median age %6h": "%1 · 품질 %2/100 · 고유 기사 %3건 · 출처 %4곳 · 24시간 이내 %5건 · 중간 연령 %6시간",
        "%1 · quality %2/100 · %3 unique headlines · %4 sources · %5 within 24h · median age %6h · company %7 / industry %8 · %9": "%1 · 품질 %2/100 · 고유 기사 %3건 · 출처 %4곳 · 24시간 이내 %5건 · 중간 연령 %6시간 · 기업 %7 / 산업 %8 · %9",
        "%1 · evidence quality %2/100 · source quality %3/100 · %4 verified company events": "%1 · 근거 품질 %2/100 · 출처 품질 %3/100 · 검증된 기업 사건 %4건",
        "%1 independent events · %2 sources · %3 syndicated copies · %4 within 24h · median age %5h": "독립 사건 %1건 · 출처 %2곳 · 재배포 기사 %3건 · 24시간 이내 %4건 · 중간 연령 %5시간",
        "Market Psychology & Risk": "시장 심리와 위험",
        "Company context": "기업 언급",
        "%1 reporting sources": "보도 출처 %1곳",
        "Evidence %1/100 · risk-adjusted %2/100 · risk penalty %3/100": "근거 신뢰도 %1/100 · 위험 반영 %2/100 · 위험 감점 %3/100",
        "Attention %1/100 (%2) · crowding %3/100 (%4) · negativity %5/100 (%6)": "관심도 %1/100 (%2) · 쏠림 %3/100 (%4) · 부정성 %5/100 (%6)",
        "Overreaction %1/100 · disagreement %2/100 · risk signals are not trade directions.": "과잉반응 %1/100 · 의견 불일치 %2/100 · 위험 신호는 매수·매도 방향을 뜻하지 않습니다.",
        "Shared news cache": "공유 뉴스 캐시",
        "Remote news": "원격 뉴스",
        "%1% · %2 news · %3 sources": "%1% · 뉴스 %2건 · 출처 %3곳",
        "%1% · %2 samples": "%1% · 표본 %2개",
        "%1% · check %2": "%1% · 확인 %2",
        "%1% · raw %2%": "%1% · 원본 %2%",
        "%1—%2 · %3 sessions · ranking is OOS-weighted": "%1—%2 · %3거래일 · 표본 외 성과 가중 순위",
        "1–5 trading days": "1~5거래일",
        "30-day API token usage ledger · prompts and responses are never stored": "30일 API 토큰 사용 기록 · 프롬프트와 응답은 저장하지 않음",
        "AI scenario only; not investment advice or an order signal.": "AI 시나리오일 뿐이며 투자 조언이나 주문 신호가 아닙니다.",
        "Adjusted %1% → %2% using %3 qualified predictions · hit %4% · Brier %5": "%1% → %2%로 보정 · 유효 예측 %3개 · 적중률 %4% · 브라이어 %5",
        "Analysis never triggers an order.": "개별 AI 분석은 주문을 실행하지 않습니다.",
        "Standalone analysis does not place orders.": "개별 AI 분석은 주문을 실행하지 않습니다.",
        "Analyzing…": "분석 중…",
        "Applied": "적용됨",
        "Choose a strategy and execution profile. Base includes commission, slippage, and sell tax.": "전략과 거래 비용 조건을 선택하세요. 기본 조건은 수수료, 슬리피지와 매도세를 반영합니다.",
        "Compare Strategies": "전략 비교",
        "Compare all strategies under one data window and execution profile.": "동일한 데이터 구간과 거래 비용 조건으로 모든 전략을 비교합니다.",
        "Comparing…": "비교 중…",
        "Completed · %1": "완료 · %1",
        "Could not complete the comparison.": "전략 비교를 완료하지 못했습니다.",
        "Could not complete the simulation.": "시뮬레이션을 완료하지 못했습니다.",
        "Equal weights": "동일 가중치",
        "High": "높음",
        "Insufficient": "불충분",
        "Limited": "제한적",
        "Loading daily closes and simulating next-session returns…": "일봉 종가를 불러와 다음 거래일 수익률을 시뮬레이션하는 중…",
        "Loading forecast journal…": "예측 기록을 불러오는 중…",
        "Local evidence": "로컬 검증",
        "Low": "낮음",
        "Moderate": "보통",
        "Measured with a ±1% neutral band. Below 60% confidence remains journaled but is excluded from qualified metrics.": "±1% 중립 구간으로 측정합니다. 신뢰도 60% 미만 예측도 기록되지만 유효 성과 지표에서는 제외됩니다.",
        "Need more data": "데이터가 더 필요함",
        "No catalysts identified.": "확인된 상승 촉매가 없습니다.",
        "No chart signal available.": "사용 가능한 차트 신호가 없습니다.",
        "No model performance history is available.": "사용 가능한 모델 성과 이력이 없습니다.",
        "No news signal available.": "사용 가능한 뉴스 신호가 없습니다.",
        "No reduction required · %1 qualified predictions · hit %2%": "감액 불필요 · 유효 예측 %1개 · 적중률 %2%",
        "No risks identified.": "확인된 위험이 없습니다.",
        "No summary available.": "요약 정보가 없습니다.",
        "Not analyzed": "분석 전",
        "Not applied": "미적용",
        "Not applied · %1 of %2 required resolved qualified predictions": "미적용 · 필요한 평가 완료 유효 예측 %2개 중 %1개",
        "Robustness is a transparent heuristic, not an expected-return forecast.": "견고성은 투명한 휴리스틱이며 기대수익률 예측이 아닙니다.",
        "Run Analysis": "분석 실행",
        "Run Backtest": "과거 성과 검증 실행",
        "Run a fresh AI analysis to start measuring forecasts.": "새 AI 분석을 실행해 예측 측정을 시작하세요.",
        "Run a strategy to compare normalized equity curves.": "전략을 실행해 정규화 자산 곡선을 비교하세요.",
        "Run analysis to build a 1–5 trading day probability scenario.": "분석을 실행해 1~5거래일 확률 시나리오를 생성하세요.",
        "Run one identical test across all strategies.": "모든 전략에 동일한 검증을 실행하세요.",
        "Running identical full-sample and walk-forward tests…": "전체 표본 및 순차 표본 외 검증을 동일 조건으로 실행 중…",
        "Running…": "실행 중…",
        "Save an OpenAI or Claude API key in Settings.": "Settings에서 OpenAI 또는 Claude API 키를 저장하세요.",
        "Single model": "단일 모델",
        "Single provider · cross-model agreement is unavailable": "단일 제공자 · 모델 간 합의도를 계산할 수 없음",
        "Unknown source": "출처 불명",
        "Untitled": "제목 없음",
        "Up %1% · Flat %2% · Down %3%": "상승 %1% · 보합 %2% · 하락 %3%",
        "Usable": "사용 가능",
        "Walk-forward uses prior sessions for selection and freezes parameters out-of-sample. It never triggers an order.": "순차 표본 외 검증은 이전 거래일로 매개변수를 선택하고 표본 외 구간에는 고정 적용합니다. 주문은 실행하지 않습니다.",
        "Walk-forward · %1": "순차 표본 외 검증 · %1",
        "Watchlist · completed daily closes · local technical ranking": "관심종목 · 확정 일봉 종가 · 로컬 기술 순위",
        "KIS adjusted daily closes": "KIS 수정주가 일봉 종가",
        "Synthetic daily sessions": "합성 일봉 거래일",
        "Visible chart range fallback": "현재 차트 구간 대체 데이터",
        "MA Trend": "이동평균 추세",
        "Long when the 5-day moving average is above the 20-day moving average.": "5일 이동평균선이 20일 이동평균선보다 높을 때 주식을 보유합니다.",
        "20D Momentum": "20일 모멘텀",
        "Long when the trailing 20-session return is positive.": "최근 20거래일 수익률이 양수일 때 주식을 보유합니다.",
        "RSI Reversion": "RSI 평균회귀",
        "Enter below RSI 35 and return to cash above RSI 55.": "RSI가 35 아래일 때 진입하고 55 위일 때 현금으로 전환합니다.",
        "Robust": "견고",
        "Mixed": "혼재",
        "Weak": "취약",
        "Each fold selects one parameter set on the prior 80 sessions, then freezes it for the next 30-session out-of-sample window.": "각 검증 구간은 이전 80거래일에서 매개변수를 고른 뒤 다음 30거래일의 표본 외 구간에 그대로 적용합니다.",
        "KIS adjusted completed daily closes": "KIS 수정주가 기준 완료 일봉 종가",
        "Synthetic adjusted completed daily closes": "합성 수정주가 기준 완료 일봉 종가",
        "Signals use only completed adjusted closes available at each session and apply to the next session. Long/cash only; commission and slippage apply on every switch, with tax on exits.": "각 시점에 확정된 수정 종가만으로 다음 거래일 신호를 계산합니다. 매수 또는 현금만 사용하며 전환마다 수수료와 슬리피지, 매도 시 세금을 반영합니다.",
        "Historical simulation only. It is not investment advice, a prediction, or an order signal.": "과거 데이터 시뮬레이션일 뿐이며 투자 조언, 예측 또는 주문 신호가 아닙니다.",
        "Strategies share identical adjusted closes and execution costs. Ranking emphasizes out-of-sample fold wins, excess return, Sharpe, drawdown, and overfit warnings.": "모든 전략에 동일한 수정 종가와 거래 비용을 적용합니다. 표본 외 구간 우위, 초과 수익률, 샤프 지수, 낙폭과 과최적화 경고를 종합해 순위를 계산합니다.",
        "This heuristic comparison is not investment advice, a prediction, or an order signal.": "이 전략 비교는 투자 조언, 예측 또는 주문 신호가 아닙니다.",
        "In-sample edge disappears OOS": "표본 내 우위가 표본 외에서 사라짐",
        "Outperforms in at most one fold": "우위를 보인 검증 구간이 1개 이하",
        "Large OOS performance decay": "표본 외 성과가 크게 감소",
        "Moderate OOS performance decay": "표본 외 성과가 다소 감소",
        "Parameter selection is unstable": "선택된 매개변수가 불안정",
        "OOS risk-adjusted return is negative": "표본 외 위험조정 수익률이 음수",
        "OOS behavior is comparatively consistent": "표본 외 성과가 비교적 일관됨",
        "Ranks 20/60-session trend, momentum, RSI, volatility, and drawdown from completed daily closes.": "확정된 일봉 종가로 20·60일 추세, 모멘텀, RSI, 변동성과 낙폭을 평가합니다.",
        "Technical ranking only. It is not investment advice, a prediction, or an order signal.": "기술 지표 기반 순위일 뿐이며 투자 조언, 예측 또는 주문 신호가 아닙니다.",
        "Predictions below the selected confidence floor are excluded from qualified metrics. Chart and news figures measure directional agreement, not causal contribution.": "선택한 최소 신뢰도보다 낮은 예측은 유효 성과 지표에서 제외됩니다. 차트와 뉴스 수치는 방향 일치도를 나타낼 뿐 인과관계를 의미하지 않습니다.",
        "Small samples are marked limited. Validation is descriptive and does not authorize an order.": "표본이 적으면 제한됨으로 표시됩니다. 검증 결과는 설명용이며 주문을 허용하지 않습니다.",
        "At least 5 resolved qualified predictions are required": "평가 완료된 유효 예측이 최소 5개 필요합니다",
        "Included in qualified scorecards": "유효 성과 지표에 포함됨",
        "Excluded from qualified scorecards until confidence improves": "신뢰도가 높아질 때까지 유효 성과 지표에서 제외됨",
        "One or more selected providers were unavailable; confidence remains qualified": "일부 AI 제공자를 사용할 수 없지만 신뢰도 기준은 충족했습니다",
        "One or more selected providers were unavailable; confidence is below the quality floor": "일부 AI 제공자를 사용할 수 없고 신뢰도가 품질 기준보다 낮습니다",
        "AI scenario only. It is not investment advice or an order signal.": "AI 시나리오이며 투자 조언이나 주문 신호가 아닙니다.",
        "Runs every minute while enabled": "켜져 있으면 1분마다 실행",
        "Off · no periodic CPU or network wake-ups": "꺼짐 · 주기적인 CPU 및 네트워크 사용 없음",
        "Background forecasts and alerts are running": "백그라운드 예측 평가와 가격 알림 실행 중",
        "Background work stopped · no periodic CPU or network wake-ups": "백그라운드 작업 중지 · 주기적인 CPU 및 네트워크 사용 없음",
        "Checking background monitoring…": "백그라운드 상태 확인 중…",
        "Starting background monitoring…": "백그라운드 모니터링 시작 중…",
        "Stopping background monitoring…": "백그라운드 모니터링 중지 중…",
        "Background monitoring unavailable": "백그라운드 모니터링을 사용할 수 없음",
        "Background worker is not installed": "백그라운드 워커가 설치되지 않음",
        "Enabled, but the timer is not active": "활성화됐지만 타이머가 작동하지 않음",
        "Checking keychain…": "키체인 확인 중…",
        "Keychain unavailable": "키체인을 사용할 수 없음",
        "Could not read keychain status": "키체인 상태를 읽지 못했습니다",
        "Save failed": "저장하지 못했습니다",
        "Saved to the system keychain": "시스템 키체인에 저장됨",
        "Could not save credential": "인증 정보를 저장하지 못했습니다",
        "Model sync failed": "모델 동기화 실패",
        "Syncing models…": "모델 동기화 중…",
        "Sync models after saving an API key": "API 키를 저장한 뒤 모델을 동기화하세요",
        "No compatible models available": "사용 가능한 호환 모델이 없습니다",
        "Not synced": "동기화되지 않음",
        "Using cached catalog": "캐시된 모델 목록 사용 중",
        "Catalog synced": "모델 목록 동기화됨",
        "Sync unavailable": "모델 동기화를 사용할 수 없음",
        "Risk policy unavailable": "위험 제한 설정을 사용할 수 없음",
        "Risk policy saved": "위험 제한 설정 저장됨",
        "Saving risk policy…": "위험 제한 설정 저장 중…",
        "Saving securely…": "안전하게 저장 중…",
        "Connecting": "연결 중",
        "Live": "실시간",
        "Stream error": "실시간 시세 연결 오류",
        "Stream parse error": "실시간 시세 처리 오류",
        "Quote unavailable": "시세를 가져올 수 없습니다",
        "Account unavailable": "계좌 정보를 가져올 수 없습니다",
        "Order failed": "주문에 실패했습니다",
        "Preflight failed": "주문 사전 확인에 실패했습니다",
        "Orders unavailable": "주문 내역을 가져올 수 없습니다",
        "Cancellation failed": "주문 취소에 실패했습니다",
        "Analysis failed": "AI 분석에 실패했습니다",
        "Activity unavailable": "거래 기록을 가져올 수 없습니다",
        "Forecast history unavailable": "예측 기록을 가져올 수 없습니다",
        "Could not delete forecast": "예측 기록을 삭제하지 못했습니다",
        "Backtest unavailable": "백테스트를 실행할 수 없습니다",
        "Strategy comparison unavailable": "전략 비교를 실행할 수 없습니다",
        "AI validation unavailable": "AI 검증을 실행할 수 없습니다",
        "AI usage unavailable": "API 사용량을 가져올 수 없습니다",
        "Screener unavailable": "종목 스크리너를 실행할 수 없습니다",
        "Watchlist unavailable": "관심종목 시세를 가져올 수 없습니다",
        "Search unavailable": "종목 검색을 사용할 수 없습니다",
        "Alert evaluation unavailable": "가격 알림을 평가할 수 없습니다",
        "Offline catalog · results may be limited": "오프라인 종목 목록 · 검색 결과가 제한될 수 있음",
        "KRX symbols must contain six digits": "한국 종목 코드는 숫자 6자리여야 합니다",
        "At least 61 completed daily closes are required for screening": "종목 선별에는 확정된 일봉 종가가 최소 61개 필요합니다",
        "Unsupported backtest strategy": "지원하지 않는 백테스트 전략입니다",
        "Unsupported backtest data source": "지원하지 않는 백테스트 데이터 소스입니다",
        "KIS backtests currently support KRX symbols only": "KIS 백테스트는 현재 한국 종목만 지원합니다",
        "Each execution cost must be between 0 and 100 bps": "각 거래 비용은 0~100bp 범위여야 합니다",
        "At least 160 completed daily closes are required for walk-forward validation": "순차 표본 외 검증에는 확정된 일봉 종가가 최소 160개 필요합니다",
        "Unsupported comparison data source": "지원하지 않는 전략 비교 데이터 소스입니다",
        "KIS comparisons currently support KRX symbols only": "KIS 전략 비교는 현재 한국 종목만 지원합니다",
        "At least 160 completed daily closes are required for strategy comparison": "전략 비교에는 확정된 일봉 종가가 최소 160개 필요합니다",
        "KIS screening currently supports KRX symbols only": "KIS 종목 선별은 현재 한국 종목만 지원합니다",
        "Production trading is locked by the global risk policy": "전역 위험 제한 설정에서 실전 거래가 잠겨 있습니다",
        "Estimated order value is unavailable": "예상 주문 금액을 계산할 수 없습니다",
        "Order exceeds the configured per-order value limit": "주문당 금액 한도를 초과했습니다",
        "Daily production buy order count limit reached": "일일 실전 매수 횟수 한도에 도달했습니다",
        "Order exceeds the configured daily production buy value": "일일 실전 매수 금액 한도를 초과했습니다",
        "Account evaluation is unavailable for the position limit check": "종목 비중 한도 확인에 필요한 계좌 평가액을 가져올 수 없습니다",
        "Order exceeds the configured position concentration limit": "종목당 최대 보유 비중을 초과했습니다",
        "Orders currently support six-digit KRX symbols only": "주문은 현재 숫자 6자리 한국 종목만 지원합니다",
        "KIS overseas orders require a limit price": "KIS 해외주식 주문은 지정가가 필요합니다",
        "Overseas symbol is invalid": "해외 종목 코드 형식이 올바르지 않습니다",
        "Unsupported overseas market": "지원하지 않는 해외 시장입니다",
        "The USD/KRW exchange rate is unavailable for the production risk check": "실전 주문 위험 검증에 필요한 원·달러 환율을 확인할 수 없습니다",
        "This overseas order is no longer cancelable": "이 해외주식 주문은 더 이상 취소할 수 없습니다",
        "Order side must be buy or sell": "주문 구분은 매수 또는 매도여야 합니다",
        "Order type must be market or limit": "주문 유형은 시장가 또는 지정가여야 합니다",
        "Order quantity is invalid": "주문 수량이 올바르지 않습니다",
        "Limit price is required": "지정가를 입력해야 합니다",
        "Estimated order price is unavailable": "예상 주문 가격을 계산할 수 없습니다",
        "Production orders require the LIVE confirmation": "실전 주문에는 LIVE 확인이 필요합니다",
        "Production cancellations require the LIVE confirmation": "실전 주문 취소에는 LIVE 확인이 필요합니다",
        "Order number is required": "주문번호가 필요합니다",
        "This order is no longer cancelable": "이 주문은 더 이상 취소할 수 없습니다",
        "This order has no cancelable quantity": "이 주문에는 취소 가능한 미체결 수량이 없습니다",
        "KIS did not return the original order organization number": "KIS에서 원주문 기관번호를 반환하지 않았습니다",
        "Forecast tracking requires a valid quote": "예측 기록에는 올바른 시세가 필요합니다",
        "Forecast evaluation requires a quote": "예측 평가에는 시세가 필요합니다",
        "Forecast evaluation requires a valid quote": "예측 평가에는 올바른 시세가 필요합니다",
        "Forecast record was not found": "예측 기록을 찾지 못했습니다",
        "Select OpenAI, Claude, or Both": "OpenAI, Claude 또는 둘 다를 선택하세요",
        "Select Quick, Balanced, or Deep": "빠르게, 균형 또는 정밀 분석을 선택하세요",
        "OpenAI API key is not saved": "OpenAI API 키가 저장되지 않았습니다",
        "Claude API key is not saved": "Claude API 키가 저장되지 않았습니다",
        "Daily history is insufficient": "일봉 데이터가 부족합니다",
        "OpenAI returned no structured analysis": "OpenAI가 구조화된 분석 결과를 반환하지 않았습니다",
        "Claude declined the analysis request": "Claude가 분석 요청을 거절했습니다",
        "Claude returned no structured analysis": "Claude가 구조화된 분석 결과를 반환하지 않았습니다",
        "KIS live data currently supports KRX symbols only": "KIS 실시간 시세는 현재 한국 종목만 지원합니다",
        "System keychain is unavailable": "시스템 키체인을 사용할 수 없습니다",
        "Credential cannot be empty": "인증 정보는 비워둘 수 없습니다",
        "KIS account must contain 8 account digits and a 2-digit product code": "KIS 계좌번호는 계좌 8자리와 상품 코드 2자리여야 합니다",
        "Could not save credential to the system keychain": "인증 정보를 시스템 키체인에 저장하지 못했습니다",
        "Could not reach the remote API": "원격 API에 연결하지 못했습니다",
        "Every live order still requires typing LIVE in its confirmation sheet.": "실전 주문마다 확인 화면에 LIVE를 입력해야 합니다.",
        "Type ENABLE LIVE to permit production order confirmation screens.": "실전 주문 확인 화면을 허용하려면 ENABLE LIVE를 입력하세요.",
        "Local audit trail · not a substitute for your KIS broker statement": "로컬 거래 기록 · KIS 공식 거래내역을 대신하지 않습니다",
        "Crossing alerts fire once, then re-arm after the price moves back.": "가격이 기준을 통과하면 한 번 알리고, 반대편으로 돌아오면 다시 알림 준비 상태가 됩니다.",
        "Secrets and account numbers are stored only in GNOME Keyring. AI cannot place orders. Production trading requires settings opt-in and LIVE confirmation for every action.": "API 키와 계좌번호는 GNOME 키체인에만 저장됩니다. 개별 AI 분석은 주문을 실행하지 않습니다. 실전 거래는 별도로 잠겨 있습니다.",
        "Secrets and account numbers stay in GNOME Keyring. AI never calls the broker directly; Paper Autopilot submits only rule-gated orders. Production remains separately locked.": "API 키와 계좌번호는 GNOME 키체인에만 저장됩니다. AI는 증권사를 직접 호출하지 않으며 모의 자동매매는 규칙 기반 안전 게이트를 통과한 주문만 전송합니다. 실전 거래는 별도로 잠겨 있습니다.",
        "Secrets and account numbers stay in GNOME Keyring. AI ranks candidates, while deterministic safety gates authorize every explicitly armed paper or live order.": "API 키와 계좌번호는 GNOME 키체인에만 저장됩니다. AI는 후보를 정렬하고, 규칙 기반 안전 게이트가 명시적으로 승인된 모의·실전 주문을 모두 검사합니다."
    })

    function text(language, source, values) {
        let key = source === undefined || source === null ? "" : String(source);
        let result = language === "ko" && ko[key] ? ko[key] : key;
        let replacements = values || [];
        for (let i = 0; i < replacements.length; i++) result = result.split("%" + (i + 1)).join(String(replacements[i]))
        return result;
    }

    function options(language, values) {
        return values.map((value) => {
            return ({
                "id": value.id,
                "label": text(language, value.label)
            });
        });
    }

}
