pragma Singleton
import Quickshell
import QtQuick

Singleton {
    readonly property var languageOptions: [
        { id: "ko", label: "한국어" },
        { id: "en", label: "English" }
    ]

    readonly property var ko: ({
        "Stocks": "주식",
        "Language": "언어",
        "Symbol": "종목 코드",
        "Market": "시장",
        "Default Range": "기본 차트 기간",
        "Data Source": "데이터 소스",
        "KIS Environment": "한국투자증권 환경",
        "Korea": "한국",
        "Quick": "빠르게",
        "Balanced": "균형",
        "Deep": "정밀",
        "Demo": "데모",
        "KIS Live": "KIS 실시간",
        "Paper": "모의투자",
        "Production": "실전투자",
        "Off": "끔",
        "Both": "둘 다",
        "Background Monitoring": "백그라운드 모니터링",
        "Global": "전체",
        "Keychain Ready": "키체인 준비됨",
        "Keychain": "키체인",
        "Trade Ready": "거래 준비됨",
        "Quotes Ready": "시세 준비됨",
        "Not Saved": "저장되지 않음",
        "App Key": "앱 키",
        "App Secret": "앱 시크릿",
        "Account Number (8-2)": "계좌번호 (8-2)",
        "Production Orders": "실전 주문",
        "Enabled": "활성화됨",
        "Locked": "잠김",
        "Risk Guard": "위험 제한",
        "Per order · KRW": "주문당 한도 · 원",
        "Daily buys · KRW": "일일 매수 한도 · 원",
        "Buy orders / day": "일일 매수 횟수",
        "Max position · %": "종목당 최대 비중 · %",
        "AI Provider": "AI 제공자",
        "Analysis Quality": "분석 품질",
        "Syncing": "동기화 중",
        "Refresh": "새로고침",
        "OpenAI API Key": "OpenAI API 키",
        "Claude API Key": "Claude API 키",
        "Saved": "저장됨",
        "Replace saved value": "저장된 값 교체",
        "Enter securely": "안전하게 입력",
        "Save": "저장",
        "Saving…": "저장 중…",
        "Lock": "잠그기",
        "Enable": "활성화",
        "Trade": "주문",
        "AI Insight": "AI 분석",
        "Portfolio": "보유 자산",
        "Buy": "매수",
        "Sell": "매도",
        "Market Order": "시장가",
        "Limit Order": "지정가",
        "Limit": "지정가",
        "SIDE": "주문 구분",
        "QUANTITY": "수량",
        "ORDER TYPE": "주문 유형",
        "LIMIT PRICE": "지정가",
        "ESTIMATED TOTAL": "예상 주문 금액",
        "ESTIMATED": "예상 금액",
        "AVAILABLE": "주문 가능",
        "POSITION AFTER": "주문 후 보유 비중",
        "Cancel": "취소",
        "Confirm": "확인",
        "Review Order": "주문 확인",
        "Submit Order": "주문 제출",
        "Keep Order": "주문 유지",
        "Cancel Remaining Order": "미체결 주문 취소",
        "Activity": "거래 기록",
        "Trade Activity": "거래 기록",
        "All": "전체",
        "Accepted": "접수 완료",
        "Failed": "실패",
        "Submitting": "제출 중",
        "Verify": "확인 필요",
        "ACCEPTED": "접수 완료",
        "FAILED": "실패",
        "SUBMITTING": "제출 중",
        "VERIFY": "확인 필요",
        "Unknown": "알 수 없음",
        "Cancel order #%1": "주문 #%1 취소",
        "%1 %2 shares of %3": "%3 · %1 %2주",
        "Broker order #%1": "증권사 주문 #%1",
        "Estimated %1": "예상 금액 %1",
        "Final broker state is unknown; verify with KIS.": "최종 주문 상태를 확인할 수 없습니다. KIS에서 확인하세요.",
        "Local audit event": "로컬 거래 기록",
        "Falls below": "하향 이탈",
        "Rises above": "상향 돌파",
        "Filled": "체결 완료",
        "Partially filled": "부분 체결",
        "Pending": "미체결",
        "Canceled": "취소됨",
        "Rejected": "거절됨",
        "Submitted": "제출됨",
        "Low overfit risk": "과최적화 위험 낮음",
        "High overfit risk": "과최적화 위험 높음",
        "Moderate risk": "과최적화 위험 보통",
        "Open": "평가 대기",
        "Correct": "적중",
        "Miss": "빗나감",
        "%1 close": "%1 종가",
        "%1 est.": "%1 예정",
        "Bullish": "상승 우세",
        "Bearish": "하락 우세",
        "Neutral": "중립",
        "Awaiting": "분석 대기",
        "Local preview only": "로컬 미리보기만 실행",
        "Production orders are locked": "실전 주문이 잠겨 있습니다",
        "Save KIS %1 API credentials in Edit": "Edit에서 KIS %1 API 인증 정보를 저장하세요",
        "Save the %1 account number in Edit": "Edit에서 %1 계좌번호를 저장하세요",
        "Checking account…": "계좌 확인 중…",
        "Account data required": "계좌 정보가 필요합니다",
        "Exceeds available buy quantity": "매수 가능 수량을 초과했습니다",
        "Exceeds sellable holdings": "매도 가능 보유 수량을 초과했습니다",
        "KIS production order · LIVE confirmation required": "KIS 실전 주문 · LIVE 확인 필요",
        "KIS paper order": "KIS 모의투자 주문",
        "Checking account and risk policy…": "계좌와 위험 제한 확인 중…",
        "Waiting for server checks…": "서버 확인 대기 중…",
        "Local preview only · no broker order will be sent": "로컬 미리보기만 실행 · 증권사에 주문을 보내지 않음",
        "KIS paper account checks passed · rechecked at submit": "KIS 모의투자 계좌 확인 완료 · 제출 시 다시 확인",
        "Risk Guard passed · daily buys %1/%2 · rechecked at submit": "위험 제한 통과 · 일일 매수 %1/%2회 · 제출 시 다시 확인",
        "Risk Guard passed · all limits are rechecked at submit": "위험 제한 통과 · 제출 시 모든 한도를 다시 확인",
        "%1 %2 shares of %3 · Local preview complete": "%3 · %1 %2주 · 로컬 미리보기 완료",
        "TOTAL": "총자산",
        "CASH": "예수금",
        "STOCKS": "주식 평가액",
        "P&L": "평가 손익",
        "Updating…": "업데이트 중…",
        "Loading local activity…": "로컬 거래 기록을 불러오는 중…",
        "No local trade activity yet.": "아직 로컬 거래 기록이 없습니다.",
        "Paper Portfolio": "모의투자 보유 자산",
        "Production Portfolio": "실전투자 보유 자산",
        "%1 holdings": "보유 종목 %1개",
        "%1 · %2 shares · Avg %3": "%1 · %2주 · 평균 %3",
        "Loading portfolio…": "보유 자산을 불러오는 중…",
        "No holdings in this account.": "이 계좌에 보유 종목이 없습니다.",
        "Paper Orders": "모의투자 주문",
        "%1 cancelable": "취소 가능 %1건",
        "Loading recent orders…": "최근 주문을 불러오는 중…",
        "No recent orders for this symbol.": "이 종목의 최근 주문이 없습니다.",
        "Sell %1 %2": "%2 %1주 매도",
        "Buy %1 %2": "%2 %1주 매수",
        "Type LIVE to cancel the unfilled quantity in your production account.": "실전 계좌의 미체결 수량을 취소하려면 LIVE를 입력하세요.",
        "Only the unfilled quantity will be canceled in your KIS mock account.": "KIS 모의투자 계좌의 미체결 수량만 취소됩니다.",
        "Canceling…": "취소 중…",
        "Cancel Remaining": "미체결 취소",
        "Review Local Preview": "로컬 미리보기 확인",
        "Review Production Order": "실전 주문 확인",
        "Review KIS Paper Order": "KIS 모의투자 주문 확인",
        "Buy %1 %2 at %3": "%2 %1주 매수 · %3",
        "Sell %1 %2 at %3": "%2 %1주 매도 · %3",
        "market price": "시장가",
        "%1 shares": "%1주",
        "Submitting…": "제출 중…",
        "Confirm Preview": "미리보기 확인",
        "Place Live Order": "실전 주문 제출",
        "Confirm Paper": "모의투자 확인",
        "Review KIS Paper": "KIS 모의투자 확인",
        "Review Live Order": "실전 주문 확인",
        "Production Locked": "실전 주문 잠김",
        "Review Preview": "미리보기 확인",
        "KIS Production · Orders locked": "KIS 실전투자 · 주문 잠김",
        "Buyable %1 · %2": "매수 가능 %1주 · %2",
        "Sellable %1 shares": "매도 가능 %1주",
        "Buying power %1": "매수 가능 금액 %1",
        "Cached": "캐시됨",
        "Orders · %1": "주문 · %1건",
        "Orders": "주문",
        "KIS WebSocket · Live": "KIS WebSocket · 실시간",
        "KIS REST · %1": "KIS REST · %1",
        "Polling": "주기적 갱신",
        "Paper market data": "모의 시장 데이터",
        "LOW": "저가",
        "HIGH": "고가",
        "VOLUME": "거래량",
        "Watchlist": "관심종목",
        "Price Alerts": "가격 알림",
        "Alerts %1": "알림 %1개",
        "Above": "상향 돌파",
        "Below": "하향 이탈",
        "Add Alert": "알림 추가",
        "No price alerts yet.": "등록된 가격 알림이 없습니다.",
        "%1 completed provider calls in the last 30 days": "최근 30일간 완료된 AI 제공자 호출 %1회",
        "%1 in · %2 out": "입력 %1 · 출력 %2",
        "%1 of %2 symbols screened · select a row to inspect": "종목 %2개 중 %1개 분석 · 행을 선택해 상세 보기",
        "%1 of 16 alerts": "알림 %1개 / 16개",
        "%1 of 8 symbols": "관심종목 %1개 / 8개",
        "%1 resolved forecasts · %2 model predictions": "평가 완료 예측 %1개 · 모델 예측 %2개",
        "%1 results": "결과 %1개",
        "%1 total": "합계 %1",
        "%1 · %2 calls": "%1 · %2회 호출",
        "%1 · %2 tokens": "%1 · 토큰 %2개",
        "%1% actual · n%2": "실제 %1% · 표본 %2개",
        "%1pp": "%1%p",
        "Add": "추가",
        "Add symbols to the watchlist, then refresh the screener.": "관심종목에 종목을 추가한 뒤 스크리너를 새로고침하세요.",
        "Add the current symbol to start a watchlist.": "현재 종목을 추가해 관심종목 목록을 시작하세요.",
        "Added": "추가됨",
        "Armed": "알림 준비됨",
        "Loading model history…": "모델 이력 불러오는 중…",
        "Loading watchlist…": "관심종목 불러오는 중…",
        "Loading…": "불러오는 중…",
        "Local metadata only · provider billing dashboards remain the source of truth for cost.": "로컬 메타데이터만 표시 · 비용은 제공자 결제 대시보드를 기준으로 확인하세요.",
        "No matching symbols.": "일치하는 종목이 없습니다.",
        "No recent calls": "최근 호출이 없습니다",
        "No recorded API usage": "기록된 API 사용량이 없습니다",
        "No resolved model predictions yet.": "아직 평가 완료된 모델 예측이 없습니다.",
        "No watchlist symbols to screen.": "분석할 관심종목이 없습니다.",
        "Pause": "일시 정지",
        "Paused": "일시 정지됨",
        "Quote error": "시세 조회 오류",
        "RSI": "RSI",
        "Ranking the watchlist from completed daily closes…": "완료된 일봉 종가를 바탕으로 관심종목 순위를 계산하는 중…",
        "Reading the local token ledger…": "로컬 토큰 사용 기록을 읽는 중…",
        "Recalculating calibration and qualified metrics…": "신뢰도 보정과 유효 성과 지표를 다시 계산하는 중…",
        "Resolved forecasts are required before calibration becomes measurable.": "보정을 측정하려면 평가 완료된 예측이 필요합니다.",
        "Resume": "다시 시작",
        "Screening unavailable": "스크리너를 사용할 수 없습니다",
        "Screening watchlist…": "관심종목 분석 중…",
        "Search Korean stocks": "국내 종목 검색",
        "Search name or symbol": "종목명 또는 종목 코드 검색",
        "Searching symbols…": "종목 검색 중…",
        "Searching…": "검색 중…",
        "Signal agreement is descriptive, not causal attribution, and never authorizes an order.": "신호 일치도는 설명용 지표일 뿐 인과관계를 의미하지 않으며 주문을 승인하지 않습니다.",
        "Target price": "목표 가격",
        "Target · %1": "목표 · %1",
        "Trend + momentum + RSI ranking from completed closes · not investment advice or an order signal.": "완료된 종가 기반 추세 + 모멘텀 + RSI 순위 · 투자 조언이나 주문 신호가 아닙니다.",
        "Triggered · waiting to re-arm": "알림 발생 · 재활성화 대기 중",
        "Unavailable": "조회 불가",
        "Unknown model": "알 수 없는 모델",
        "usable": "사용 가능",
        "limited": "표본 부족",
        "unavailable": "사용 불가",
        "Updating quotes…": "시세 업데이트 중…",
        "Waiting for recross": "가격 재교차 대기 중",
        "Already in your watchlist.": "이미 관심종목에 있습니다.",
        "Watchlist is limited to 8 symbols.": "관심종목은 최대 8개까지 추가할 수 있습니다.",
        "Remove this symbol's price alerts first.": "이 종목의 가격 알림을 먼저 삭제하세요.",
        "Enter a valid target price.": "올바른 목표 가격을 입력하세요.",
        "Price alerts are limited to 16.": "가격 알림은 최대 16개까지 추가할 수 있습니다.",
        "Watchlist is full. Remove a symbol before adding this alert.": "관심종목이 가득 찼습니다. 종목을 삭제한 뒤 알림을 추가하세요.",
        "That price alert already exists.": "동일한 가격 알림이 이미 있습니다.",
        "Quant Lab": "퀀트 분석",
        "Forecasts": "예측 기록",
        "Backtest": "과거 성과 검증",
        "Compare": "전략 비교",
        "AI Eval": "AI 검증",
        "Usage": "API 사용량",
        "Screener": "종목 선별",
        "Details": "상세 보기",
        "Scenario": "전망",
        "Confidence": "신뢰도",
        "Walk-forward": "순차 표본 외 검증",
        "QUALIFIED HIT": "유효 예측 적중률",
        "QUALIFIED / RESOLVED": "유효 / 평가 완료",
        "OPEN": "평가 대기",
        "BRIER · LOWER BETTER": "예측 확률 오차 · 낮을수록 좋음",
        "AI Scenario Report": "AI 시나리오 분석",
        "SCENARIO": "전망",
        "CONFIDENCE": "신뢰도",
        "UP / FLAT / DOWN": "상승 / 보합 / 하락",
        "SOURCES": "분석 출처",
        "Summary": "요약",
        "Provider Status": "AI 제공자 상태",
        "Token Usage": "토큰 사용량",
        "Historical Confidence Calibration": "과거 신뢰도 보정",
        "Ensemble Agreement": "모델 합의도",
        "Historical Model Weighting": "과거 성과 기반 모델 가중치",
        "Chart Signal": "차트 신호",
        "News Signal": "뉴스 신호",
        "News Evidence Quality": "뉴스 근거 품질",
        "Chart Metrics": "차트 지표",
        "20D RETURN": "20일 수익률",
        "MA SPREAD": "이동평균선 간격",
        "20D ANN VOL": "20일 연환산 변동성",
        "RSI 14": "RSI 14",
        "60D RETURN": "60일 수익률",
        "PRICE / MA60": "현재가 / 60일선",
        "60D DRAWDOWN": "60일 최대 낙폭",
        "TREND REGIME": "추세 국면",
        "Walk-forward Evidence": "순차 표본 외 검증 근거",
        "HIT RATE": "적중률",
        "SAMPLES": "표본 수",
        "TEST RETURN": "검증 수익률",
        "MAX DRAWDOWN": "최대 낙폭",
        "Catalysts": "상승 촉매",
        "Risks": "주요 위험",
        "Recent News Evidence": "최근 뉴스 근거",
        "No recent headlines were available.": "최근 뉴스 제목을 가져오지 못했습니다.",
        "Trend": "추세",
        "Momentum": "모멘텀",
        "Ideal": "이상적",
        "Base": "기본",
        "Stress": "비용 악화",
        "STRATEGY": "전략 수익률",
        "BUY & HOLD": "단순 보유",
        "EXCESS": "초과 수익률",
        "WF OOS RETURN": "표본 외 수익률",
        "WF OOS EXCESS": "표본 외 초과 수익률",
        "FOLD WINS": "구간 우위",
        "WF SHARPE": "표본 외 샤프 지수",
        "Strategy": "전략",
        "Buy & Hold": "단순 보유",
        "Same adjusted closes · same execution costs": "동일한 수정주가 · 동일한 거래 비용",
        "BEST OOS BALANCE": "최고 표본 외 균형",
        "ROBUSTNESS": "견고성",
        "HIGH OVERFIT RISK": "높은 과최적화 위험",
        "STRATEGIES": "전략 수",
        "Inspect": "상세 보기",
        "OOS": "표본 외",
        "FOLDS": "검증 구간",
        "OOS MDD": "표본 외 최대 낙폭",
        "P/L FACTOR": "수익계수",
        "SWITCH/YR": "연간 매매 전환",
        "SCREENED": "분석 종목",
        "BULLISH": "상승 우세",
        "NEUTRAL": "중립",
        "BEARISH": "하락 우세",
        "20D": "20일",
        "VOL": "변동성",
        "DD 60D": "60일 낙폭",
        "API CALLS": "API 호출",
        "BILLABLE INPUT": "과금 입력 토큰",
        "OUTPUT": "출력 토큰",
        "TOTAL TOKENS": "전체 토큰",
        "MODEL USAGE": "모델별 사용량",
        "RECENT CALLS": "최근 호출",
        "Qualified confidence floor": "유효 예측 최소 신뢰도",
        "Lower-confidence predictions remain journaled but are excluded from qualified metrics.": "기준보다 신뢰도가 낮은 예측도 기록되지만 유효 성과 지표에서는 제외됩니다.",
        "QUALIFIED HIT RATE": "유효 예측 적중률",
        "QUALIFIED BRIER": "유효 예측 확률 오차",
        "CALIBRATION ECE": "보정 오차(ECE)",
        "QUALIFIED / EXCLUDED": "유효 / 제외",
        "Chart direction agreement": "차트 방향 일치도",
        "News direction agreement": "뉴스 방향 일치도",
        "MODEL PERFORMANCE · RESOLVED PREDICTIONS": "모델 성과 · 평가 완료 예측",
        "QUAL HIT": "유효 적중률",
        "BRIER": "확률 오차",
        "CAL GAP": "보정 오차",
        "N / EXCL": "표본 / 제외",
        "QUALITY": "품질",
        "CONFIDENCE 0–49": "신뢰도 0–49",
        "CONFIDENCE 50–69": "신뢰도 50–69",
        "CONFIDENCE 70–100": "신뢰도 70–100",
        "QUAL COVER": "유효 포함률",
        "AVG CONF": "평균 신뢰도",
        " · %1 · %2 sessions": " · %1 · %2거래일",
        " · Calibrated": " · 보정됨",
        " · Journaled": " · 기록됨",
        " · Low confidence": " · 낮은 신뢰도",
        " · Model conflict": " · 모델 판단 충돌",
        " · Partial provider result": " · 일부 제공자 결과",
        " · Weighted ensemble": " · 가중 앙상블",
        " · bullish/bearish conflict": " · 상승·하락 판단 충돌",
        " · cached %1": " · 캐시 %1",
        " · hit %1%": " · 적중률 %1%",
        " · low confidence": " · 낮은 신뢰도",
        " · reasoning %1": " · 추론 %1",
        "%1  Models: %2": "%1  모델: %2",
        "%1 %2": "%1 %2",
        "%1 %2 %3": "%1 %2 %3",
        "%1 %2% · n%3": "%1 %2% · 표본 %3개",
        "%1 API calls · input %2 · output %3 · total %4": "API 호출 %1회 · 입력 %2 · 출력 %3 · 합계 %4",
        "%1 agreement · score %2/100 · probability disagreement %3pp · confidence %4% → %5%": "%1 합의 · 점수 %2/100 · 확률 차이 %3%p · 신뢰도 %4% → %5%",
        "%1 news · %2 sources": "뉴스 %1건 · 출처 %2곳",
        "%1 unavailable · %2": "%1 사용 불가 · %2",
        "%1 · %2": "%1 · %2",
        "%1 · %2%3": "%1 · %2%3",
        "%1 · %2—%3 · %4 sessions · %5/%6/%7 bps commission/slippage/tax": "%1 · %2—%3 · %4거래일 · 수수료/슬리피지/매도세 %5/%6/%7bp",
        "%1 · 5 trading-day checks · local journal": "%1 · 5거래일 검증 · 로컬 기록",
        "%1 · daily close simulation · no look-ahead": "%1 · 일봉 종가 시뮬레이션 · 미래 데이터 미사용",
        "%1 · identical data and costs · OOS ranking": "%1 · 동일 데이터·비용 · 표본 외 순위",
        "%1 · model calibration · confidence quality gate": "%1 · 모델 보정 · 신뢰도 품질 기준",
        "%1 · quality %2/100 · %3 unique headlines · %4 sources · %5 within 24h · median age %6h": "%1 · 품질 %2/100 · 고유 기사 %3건 · 출처 %4곳 · 24시간 이내 %5건 · 중간 연령 %6시간",
        "%1% · %2 news · %3 sources": "%1% · 뉴스 %2건 · 출처 %3곳",
        "%1% · %2 samples": "%1% · 표본 %2개",
        "%1% · check %2": "%1% · 확인 %2",
        "%1% · raw %2%": "%1% · 원본 %2%",
        "%1—%2 · %3 sessions · ranking is OOS-weighted": "%1—%2 · %3거래일 · 표본 외 성과 가중 순위",
        "1–5 trading days": "1~5거래일",
        "30-day API token usage ledger · prompts and responses are never stored": "30일 API 토큰 사용 기록 · 프롬프트와 응답은 저장하지 않음",
        "AI scenario only; not investment advice or an order signal.": "AI 시나리오일 뿐이며 투자 조언이나 주문 신호가 아닙니다.",
        "Adjusted %1% → %2% using %3 qualified predictions · hit %4% · Brier %5": "%1% → %2%로 보정 · 유효 예측 %3개 · 적중률 %4% · 브라이어 %5",
        "Analysis never triggers an order.": "AI 분석은 주문을 실행하지 않습니다.",
        "Analyzing…": "분석 중…",
        "Applied": "적용됨",
        "Choose a strategy and execution profile. Base includes commission, slippage, and sell tax.": "전략과 거래 비용 조건을 선택하세요. 기본 조건은 수수료, 슬리피지와 매도세를 반영합니다.",
        "Compare Strategies": "전략 비교",
        "Compare all strategies under one data window and execution profile.": "동일한 데이터 구간과 거래 비용 조건으로 모든 전략을 비교합니다.",
        "Comparing…": "비교 중…",
        "Completed · %1": "완료 · %1",
        "Could not complete the comparison.": "전략 비교를 완료하지 못했습니다.",
        "Could not complete the simulation.": "시뮬레이션을 완료하지 못했습니다.",
        "Equal weights": "동일 가중치",
        "High": "높음",
        "Insufficient": "불충분",
        "Limited": "제한적",
        "Loading daily closes and simulating next-session returns…": "일봉 종가를 불러와 다음 거래일 수익률을 시뮬레이션하는 중…",
        "Loading forecast journal…": "예측 기록을 불러오는 중…",
        "Local evidence": "로컬 검증",
        "Low": "낮음",
        "Measured with a ±1% neutral band. Below 60% confidence remains journaled but is excluded from qualified metrics.": "±1% 중립 구간으로 측정합니다. 신뢰도 60% 미만 예측도 기록되지만 유효 성과 지표에서는 제외됩니다.",
        "Need more data": "데이터가 더 필요함",
        "No catalysts identified.": "확인된 상승 촉매가 없습니다.",
        "No chart signal available.": "사용 가능한 차트 신호가 없습니다.",
        "No model performance history is available.": "사용 가능한 모델 성과 이력이 없습니다.",
        "No news signal available.": "사용 가능한 뉴스 신호가 없습니다.",
        "No reduction required · %1 qualified predictions · hit %2%": "감액 불필요 · 유효 예측 %1개 · 적중률 %2%",
        "No risks identified.": "확인된 위험이 없습니다.",
        "No summary available.": "요약 정보가 없습니다.",
        "Not analyzed": "분석 전",
        "Not applied": "미적용",
        "Not applied · %1 of %2 required resolved qualified predictions": "미적용 · 필요한 평가 완료 유효 예측 %2개 중 %1개",
        "Robustness is a transparent heuristic, not an expected-return forecast.": "견고성은 투명한 휴리스틱이며 기대수익률 예측이 아닙니다.",
        "Run Analysis": "분석 실행",
        "Run Backtest": "과거 성과 검증 실행",
        "Run a fresh AI analysis to start measuring forecasts.": "새 AI 분석을 실행해 예측 측정을 시작하세요.",
        "Run a strategy to compare normalized equity curves.": "전략을 실행해 정규화 자산 곡선을 비교하세요.",
        "Run analysis to build a 1–5 trading day probability scenario.": "분석을 실행해 1~5거래일 확률 시나리오를 생성하세요.",
        "Run one identical test across all strategies.": "모든 전략에 동일한 검증을 실행하세요.",
        "Running identical full-sample and walk-forward tests…": "전체 표본 및 순차 표본 외 검증을 동일 조건으로 실행 중…",
        "Running…": "실행 중…",
        "Save an OpenAI or Claude API key in Edit.": "편집에서 OpenAI 또는 Claude API 키를 저장하세요.",
        "Single model": "단일 모델",
        "Single provider · cross-model agreement is unavailable": "단일 제공자 · 모델 간 합의도를 계산할 수 없음",
        "Unknown source": "출처 불명",
        "Untitled": "제목 없음",
        "Up %1% · Flat %2% · Down %3%": "상승 %1% · 보합 %2% · 하락 %3%",
        "Usable": "사용 가능",
        "Walk-forward uses prior sessions for selection and freezes parameters out-of-sample. It never triggers an order.": "순차 표본 외 검증은 이전 거래일로 매개변수를 선택하고 표본 외 구간에는 고정 적용합니다. 주문은 실행하지 않습니다.",
        "Walk-forward · %1": "순차 표본 외 검증 · %1",
        "Watchlist · completed daily closes · local technical ranking": "관심종목 · 확정 일봉 종가 · 로컬 기술 순위",
        "KIS adjusted daily closes": "KIS 수정주가 일봉 종가",
        "Synthetic daily sessions": "합성 일봉 거래일",
        "Visible chart range fallback": "현재 차트 구간 대체 데이터",
        "MA Trend": "이동평균 추세",
        "Long when the 5-day moving average is above the 20-day moving average.": "5일 이동평균선이 20일 이동평균선보다 높을 때 주식을 보유합니다.",
        "20D Momentum": "20일 모멘텀",
        "Long when the trailing 20-session return is positive.": "최근 20거래일 수익률이 양수일 때 주식을 보유합니다.",
        "RSI Reversion": "RSI 평균회귀",
        "Enter below RSI 35 and return to cash above RSI 55.": "RSI가 35 아래일 때 진입하고 55 위일 때 현금으로 전환합니다.",
        "Robust": "견고",
        "Mixed": "혼재",
        "Weak": "취약",
        "Each fold selects one parameter set on the prior 80 sessions, then freezes it for the next 30-session out-of-sample window.": "각 검증 구간은 이전 80거래일에서 매개변수를 고른 뒤 다음 30거래일의 표본 외 구간에 그대로 적용합니다.",
        "KIS adjusted completed daily closes": "KIS 수정주가 기준 완료 일봉 종가",
        "Synthetic adjusted completed daily closes": "합성 수정주가 기준 완료 일봉 종가",
        "Signals use only completed adjusted closes available at each session and apply to the next session. Long/cash only; commission and slippage apply on every switch, with tax on exits.": "각 시점에 확정된 수정 종가만으로 다음 거래일 신호를 계산합니다. 매수 또는 현금만 사용하며 전환마다 수수료와 슬리피지, 매도 시 세금을 반영합니다.",
        "Historical simulation only. It is not investment advice, a prediction, or an order signal.": "과거 데이터 시뮬레이션일 뿐이며 투자 조언, 예측 또는 주문 신호가 아닙니다.",
        "Strategies share identical adjusted closes and execution costs. Ranking emphasizes out-of-sample fold wins, excess return, Sharpe, drawdown, and overfit warnings.": "모든 전략에 동일한 수정 종가와 거래 비용을 적용합니다. 표본 외 구간 우위, 초과 수익률, 샤프 지수, 낙폭과 과최적화 경고를 종합해 순위를 계산합니다.",
        "This heuristic comparison is not investment advice, a prediction, or an order signal.": "이 전략 비교는 투자 조언, 예측 또는 주문 신호가 아닙니다.",
        "In-sample edge disappears OOS": "표본 내 우위가 표본 외에서 사라짐",
        "Outperforms in at most one fold": "우위를 보인 검증 구간이 1개 이하",
        "Large OOS performance decay": "표본 외 성과가 크게 감소",
        "Moderate OOS performance decay": "표본 외 성과가 다소 감소",
        "Parameter selection is unstable": "선택된 매개변수가 불안정",
        "OOS risk-adjusted return is negative": "표본 외 위험조정 수익률이 음수",
        "OOS behavior is comparatively consistent": "표본 외 성과가 비교적 일관됨",
        "Ranks 20/60-session trend, momentum, RSI, volatility, and drawdown from completed daily closes.": "확정된 일봉 종가로 20·60일 추세, 모멘텀, RSI, 변동성과 낙폭을 평가합니다.",
        "Technical ranking only. It is not investment advice, a prediction, or an order signal.": "기술 지표 기반 순위일 뿐이며 투자 조언, 예측 또는 주문 신호가 아닙니다.",
        "Predictions below the selected confidence floor are excluded from qualified metrics. Chart and news figures measure directional agreement, not causal contribution.": "선택한 최소 신뢰도보다 낮은 예측은 유효 성과 지표에서 제외됩니다. 차트와 뉴스 수치는 방향 일치도를 나타낼 뿐 인과관계를 의미하지 않습니다.",
        "Small samples are marked limited. Validation is descriptive and does not authorize an order.": "표본이 적으면 제한됨으로 표시됩니다. 검증 결과는 설명용이며 주문을 허용하지 않습니다.",
        "At least 5 resolved qualified predictions are required": "평가 완료된 유효 예측이 최소 5개 필요합니다",
        "Included in qualified scorecards": "유효 성과 지표에 포함됨",
        "Excluded from qualified scorecards until confidence improves": "신뢰도가 높아질 때까지 유효 성과 지표에서 제외됨",
        "One or more selected providers were unavailable; confidence remains qualified": "일부 AI 제공자를 사용할 수 없지만 신뢰도 기준은 충족했습니다",
        "One or more selected providers were unavailable; confidence is below the quality floor": "일부 AI 제공자를 사용할 수 없고 신뢰도가 품질 기준보다 낮습니다",
        "AI scenario only. It is not investment advice or an order signal.": "AI 시나리오이며 투자 조언이나 주문 신호가 아닙니다.",
        "Runs every minute while enabled": "켜져 있으면 1분마다 실행",
        "Off · no periodic CPU or network wake-ups": "꺼짐 · 주기적인 CPU 및 네트워크 사용 없음",
        "Background forecasts and alerts are running": "백그라운드 예측 평가와 가격 알림 실행 중",
        "Background work stopped · no periodic CPU or network wake-ups": "백그라운드 작업 중지 · 주기적인 CPU 및 네트워크 사용 없음",
        "Checking background monitoring…": "백그라운드 상태 확인 중…",
        "Starting background monitoring…": "백그라운드 모니터링 시작 중…",
        "Stopping background monitoring…": "백그라운드 모니터링 중지 중…",
        "Background monitoring unavailable": "백그라운드 모니터링을 사용할 수 없음",
        "Background worker is not installed": "백그라운드 워커가 설치되지 않음",
        "Enabled, but the timer is not active": "활성화됐지만 타이머가 작동하지 않음",
        "Checking keychain…": "키체인 확인 중…",
        "Keychain unavailable": "키체인을 사용할 수 없음",
        "Could not read keychain status": "키체인 상태를 읽지 못했습니다",
        "Save failed": "저장하지 못했습니다",
        "Saved to the system keychain": "시스템 키체인에 저장됨",
        "Could not save credential": "인증 정보를 저장하지 못했습니다",
        "Model sync failed": "모델 동기화 실패",
        "Syncing models…": "모델 동기화 중…",
        "Sync models after saving an API key": "API 키를 저장한 뒤 모델을 동기화하세요",
        "No compatible models available": "사용 가능한 호환 모델이 없습니다",
        "Not synced": "동기화되지 않음",
        "Using cached catalog": "캐시된 모델 목록 사용 중",
        "Catalog synced": "모델 목록 동기화됨",
        "Sync unavailable": "모델 동기화를 사용할 수 없음",
        "Risk policy unavailable": "위험 제한 설정을 사용할 수 없음",
        "Risk policy saved": "위험 제한 설정 저장됨",
        "Saving risk policy…": "위험 제한 설정 저장 중…",
        "Saving securely…": "안전하게 저장 중…",
        "Connecting": "연결 중",
        "Live": "실시간",
        "Stream error": "실시간 시세 연결 오류",
        "Stream parse error": "실시간 시세 처리 오류",
        "Quote unavailable": "시세를 가져올 수 없습니다",
        "Account unavailable": "계좌 정보를 가져올 수 없습니다",
        "Order failed": "주문에 실패했습니다",
        "Preflight failed": "주문 사전 확인에 실패했습니다",
        "Orders unavailable": "주문 내역을 가져올 수 없습니다",
        "Cancellation failed": "주문 취소에 실패했습니다",
        "Analysis failed": "AI 분석에 실패했습니다",
        "Activity unavailable": "거래 기록을 가져올 수 없습니다",
        "Forecast history unavailable": "예측 기록을 가져올 수 없습니다",
        "Could not delete forecast": "예측 기록을 삭제하지 못했습니다",
        "Backtest unavailable": "백테스트를 실행할 수 없습니다",
        "Strategy comparison unavailable": "전략 비교를 실행할 수 없습니다",
        "AI validation unavailable": "AI 검증을 실행할 수 없습니다",
        "AI usage unavailable": "API 사용량을 가져올 수 없습니다",
        "Screener unavailable": "종목 스크리너를 실행할 수 없습니다",
        "Watchlist unavailable": "관심종목 시세를 가져올 수 없습니다",
        "Search unavailable": "종목 검색을 사용할 수 없습니다",
        "Alert evaluation unavailable": "가격 알림을 평가할 수 없습니다",
        "Offline catalog · results may be limited": "오프라인 종목 목록 · 검색 결과가 제한될 수 있음",
        "KRX symbols must contain six digits": "한국 종목 코드는 숫자 6자리여야 합니다",
        "At least 61 completed daily closes are required for screening": "종목 선별에는 확정된 일봉 종가가 최소 61개 필요합니다",
        "Unsupported backtest strategy": "지원하지 않는 백테스트 전략입니다",
        "Unsupported backtest data source": "지원하지 않는 백테스트 데이터 소스입니다",
        "KIS backtests currently support KRX symbols only": "KIS 백테스트는 현재 한국 종목만 지원합니다",
        "Each execution cost must be between 0 and 100 bps": "각 거래 비용은 0~100bp 범위여야 합니다",
        "At least 160 completed daily closes are required for walk-forward validation": "순차 표본 외 검증에는 확정된 일봉 종가가 최소 160개 필요합니다",
        "Unsupported comparison data source": "지원하지 않는 전략 비교 데이터 소스입니다",
        "KIS comparisons currently support KRX symbols only": "KIS 전략 비교는 현재 한국 종목만 지원합니다",
        "At least 160 completed daily closes are required for strategy comparison": "전략 비교에는 확정된 일봉 종가가 최소 160개 필요합니다",
        "KIS screening currently supports KRX symbols only": "KIS 종목 선별은 현재 한국 종목만 지원합니다",
        "Production trading is locked by the global risk policy": "전역 위험 제한 설정에서 실전 거래가 잠겨 있습니다",
        "Estimated order value is unavailable": "예상 주문 금액을 계산할 수 없습니다",
        "Order exceeds the configured per-order value limit": "주문당 금액 한도를 초과했습니다",
        "Daily production buy order count limit reached": "일일 실전 매수 횟수 한도에 도달했습니다",
        "Order exceeds the configured daily production buy value": "일일 실전 매수 금액 한도를 초과했습니다",
        "Account evaluation is unavailable for the position limit check": "종목 비중 한도 확인에 필요한 계좌 평가액을 가져올 수 없습니다",
        "Order exceeds the configured position concentration limit": "종목당 최대 보유 비중을 초과했습니다",
        "Orders currently support six-digit KRX symbols only": "주문은 현재 숫자 6자리 한국 종목만 지원합니다",
        "Order side must be buy or sell": "주문 구분은 매수 또는 매도여야 합니다",
        "Order type must be market or limit": "주문 유형은 시장가 또는 지정가여야 합니다",
        "Order quantity is invalid": "주문 수량이 올바르지 않습니다",
        "Limit price is required": "지정가를 입력해야 합니다",
        "Estimated order price is unavailable": "예상 주문 가격을 계산할 수 없습니다",
        "Production orders require the LIVE confirmation": "실전 주문에는 LIVE 확인이 필요합니다",
        "Production cancellations require the LIVE confirmation": "실전 주문 취소에는 LIVE 확인이 필요합니다",
        "Order number is required": "주문번호가 필요합니다",
        "This order is no longer cancelable": "이 주문은 더 이상 취소할 수 없습니다",
        "This order has no cancelable quantity": "이 주문에는 취소 가능한 미체결 수량이 없습니다",
        "KIS did not return the original order organization number": "KIS에서 원주문 기관번호를 반환하지 않았습니다",
        "Forecast tracking requires a valid quote": "예측 기록에는 올바른 시세가 필요합니다",
        "Forecast evaluation requires a quote": "예측 평가에는 시세가 필요합니다",
        "Forecast evaluation requires a valid quote": "예측 평가에는 올바른 시세가 필요합니다",
        "Forecast record was not found": "예측 기록을 찾지 못했습니다",
        "Select OpenAI, Claude, or Both": "OpenAI, Claude 또는 둘 다를 선택하세요",
        "Select Quick, Balanced, or Deep": "빠르게, 균형 또는 정밀 분석을 선택하세요",
        "OpenAI API key is not saved": "OpenAI API 키가 저장되지 않았습니다",
        "Claude API key is not saved": "Claude API 키가 저장되지 않았습니다",
        "Daily history is insufficient": "일봉 데이터가 부족합니다",
        "OpenAI returned no structured analysis": "OpenAI가 구조화된 분석 결과를 반환하지 않았습니다",
        "Claude declined the analysis request": "Claude가 분석 요청을 거절했습니다",
        "Claude returned no structured analysis": "Claude가 구조화된 분석 결과를 반환하지 않았습니다",
        "KIS live data currently supports KRX symbols only": "KIS 실시간 시세는 현재 한국 종목만 지원합니다",
        "System keychain is unavailable": "시스템 키체인을 사용할 수 없습니다",
        "Credential cannot be empty": "인증 정보는 비워둘 수 없습니다",
        "KIS account must contain 8 account digits and a 2-digit product code": "KIS 계좌번호는 계좌 8자리와 상품 코드 2자리여야 합니다",
        "Could not save credential to the system keychain": "인증 정보를 시스템 키체인에 저장하지 못했습니다",
        "Could not reach the remote API": "원격 API에 연결하지 못했습니다",
        "Every live order still requires typing LIVE in its confirmation sheet.": "실전 주문마다 확인 화면에 LIVE를 입력해야 합니다.",
        "Type ENABLE LIVE to permit production order confirmation screens.": "실전 주문 확인 화면을 허용하려면 ENABLE LIVE를 입력하세요.",
        "Local audit trail · not a substitute for your KIS broker statement": "로컬 거래 기록 · KIS 공식 거래내역을 대신하지 않습니다",
        "Crossing alerts fire once, then re-arm after the price moves back.": "가격이 기준을 통과하면 한 번 알리고, 반대편으로 돌아오면 다시 알림 준비 상태가 됩니다.",
        "Secrets and account numbers are stored only in GNOME Keyring. AI cannot place orders. Production trading requires settings opt-in and LIVE confirmation for every action.": "API 키와 계좌번호는 GNOME 키체인에만 저장됩니다. AI는 주문을 실행할 수 없습니다. 실전 거래는 설정에서 허용한 뒤 모든 동작마다 LIVE 확인이 필요합니다."
    })

    function text(language, source, values) {
        let key = source === undefined || source === null ? "" : String(source)
        let result = language === "ko" && ko[key] ? ko[key] : key
        let replacements = values || []
        for (let i = 0; i < replacements.length; i++)
            result = result.split("%" + (i + 1)).join(String(replacements[i]))
        return result
    }

    function options(language, values) {
        return values.map(value => ({ id: value.id, label: text(language, value.label) }))
    }
}
