splash = false
ipc = on

preload = /home/sejunlee/junk/wallpaper/wallpaper.png
wallpaper = eDP-1, /home/sejunlee/junk/wallpaper/wallpaper.png
wallpaper = DP-2, /home/sejunlee/junk/wallpaper/wallpaper.png
wallpaper = HDMI-A-1, /home/sejunlee/junk/wallpaper/wallpaper.png
