# #######################################################################################
# MAIN HYPRLAND CONFIG
# #######################################################################################

# Main Modifier
$mainMod = SUPER
$terminal = kitty
$fileManager = nautilus

# Source external config files
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/configs/autostart.conf
source = ~/.config/hypr/configs/env.conf
source = ~/.config/hypr/configs/theme.conf
source = ~/.config/hypr/configs/input.conf
source = ~/.config/hypr/configs/keybindings.conf
source = ~/.config/hypr/configs/windowrules.conf

# XWayland Specifics
xwayland {
  force_zero_scaling = true
}

# Debug (Optional)
#debug:disable_scale_checks = true
