splash = false
ipc = on

preload = /home/sejunlee/junk/wallpaper/wallpaper.jpeg
wallpaper = eDP-1, contain:/home/sejunlee/junk/wallpaper/wallpaper.jpeg
wallpaper = DP-2, contain:/home/sejunlee/junk/wallpaper/wallpaper.jpeg
wallpaper = HDMI-A-1, contain:/home/sejunlee/junk/wallpaper/wallpaper.jpeg
