-- Generated by nwg-displays on 2026-07-06 at 10:39:11. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    disabled = true
})
hl.monitor({
    output = "DP-1",
    mode = "3840x2160@60.0",
    position = "0x0",
    scale = 1.5
})
