-- Generated by nwg-displays on 2026-06-15 at 11:49:26. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "3840x2400@60.0",
    position = "314x1440",
    scale = 2.0,
    bitdepth = 10
})
hl.monitor({
    output = "DP-1",
    mode = "3840x2160@60.0",
    position = "0x0",
    scale = 1.5
})
