-- Generated by nwg-displays on 2026-05-27 at 15:13:05. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "3840x2400@60.0",
    position = "314x1440",
    scale = 2.0,
    bitdepth = 10
})
hl.monitor({
    output = "DP-2",
    mode = "3840x2160@60.0",
    position = "2234x80",
    scale = 1.5,
    transform = 1
})
