#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)

exec-once = nm-applet & blueman-applet
exec-once = waybar & fcitx5
exec-once = ~/.config/hypr/scripts/wallpaper.sh
exec-once = hypridle
exec-once = env __EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json VK_DRIVER_FILES=/usr/share/vulkan/icd.d/intel_icd.x86_64.json swaync
exec-once = sticky-notes
exec-once = wl-clip-persist --clipboard regular
exec-once = hyprshell run &
exec-once = xembedsniproxy
exec-once = ~/.config/ags-osd/config.tsx
