#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)

exec-once = nm-applet & blueman-applet
exec-once = waybar & fcitx5
exec-once = ~/.config/hypr/scripts/wallpaper.sh
exec-once = sh -lc 'systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_RUNTIME_DIR DBUS_SESSION_BUS_ADDRESS; systemctl --user start pipewire pipewire-pulse wireplumber'
exec-once = hypridle & swaync
exec-once = sticky-notes
exec-once = wl-clip-persist --clipboard regular
exec-once = xembedsniproxy
