#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant =
    kb_model =
    #kb_options = altwin:swap_alt_win
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = true
	disable_while_typing = true
	tap-to-click = false
    }
}

cursor {
    inactive_timeout = 3
    no_hardware_cursors = 0
}

# See https://wiki.hypr.land/Configuring/Gestures
gesture = 3, horizontal, workspace

# Example per-device config
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
device {
    name = logitech-mx-master-3s
    scroll_factor = 1.0        # 방향 뒤집고 싶으면 -1.0
    natural_scroll = true     # 터치패드처럼 ‘자연 스크롤’ 원하면 이걸 켜고 위는 1.0 유지
}

device {
    name = logitech-usb-receiver-mouse
    scroll_factor = 1.0
    natural_scroll = true
}

device {
    name = tpps/2-elan-trackpoint
    sensitivity = -0.5
}
    
device {
	name = syna800e:00-06cb:ce67-touchpad
	sensitivity = 0.15
	scroll_factor = 0.4
}

